/* 
 * File:   CCSDSFormatDescription.hpp
 * Author: matthewwilkins
 *
 * Created on September 3, 2009, 4:58 AM
 */

#ifndef _CCSDSOBTYPE_HPP
#define	_CCSDSOBTYPE_HPP

#include "Obtype.hpp"
#include "CCSDSObtype.hpp"

using namespace CCSDSObtype;

class CCSDSTDMObtype : public Obtype
{   
    
public :
    
    CCSDSTDMObtype();
    ~CCSDSTDMObtype();
    	
    bool IsParameterRequired(const Integer id) const;    
	
    enum CCSDS_TDM_DATA_REPS
    {
	CCSDS_TDM_VERSION_ID,
	CCSDS_TDM_CREATIONDATE_ID,
	CCSDS_TDM_ORIGINATOR_ID,
	CCSDS_TDM_HEADERCOMMENTS_ID,
	CCSDS_TDM_METADATACOMMENTS_ID,
	CCSDS_TDM_TIMESYSTEM_ID,
	CCSDS_TDM_STARTTIME_ID,
	CCSDS_TDM_STOPTIME_ID,
	CCSDS_TDM_PARTICIPANT1_ID,
	CCSDS_TDM_PARTICIPANT2_ID,
	CCSDS_TDM_PARTICIPANT3_ID,
	CCSDS_TDM_PARTICIPANT4_ID,
	CCSDS_TDM_PARTICIPANT5_ID,
	CCSDS_TDM_MODE_ID,
	CCSDS_TDM_PATH_ID,
	CCSDS_TDM_PATH1_ID,
	CCSDS_TDM_PATH2_ID,
	CCSDS_TDM_TRANSMITBAND_ID,
	CCSDS_TDM_RECEIVEBAND_ID,
	CCSDS_TDM_TURNAROUNDNUMERATOR_ID,
	CCSDS_TDM_TURNAROUNDDENOMINATOR_ID,
	CCSDS_TDM_TIMETAGREF_ID,
	CCSDS_TDM_INTEGRATIONINTERVAL_ID,
	CCSDS_TDM_INTEGRATIONREF_ID,
	CCSDS_TDM_FREQUENCYOFFSET_ID,
	CCSDS_TDM_RANGEMODE_ID,
	CCSDS_TDM_RANGEMODULUS_ID,
	CCSDS_TDM_RANGEUNITS_ID,
	CCSDS_TDM_ANGLETYPE_ID,	
	CCSDS_TDM_REFERENCEFRAME_ID,
	CCSDS_TDM_TRANSMITDELAY1_ID,
	CCSDS_TDM_TRANSMITDELAY2_ID,
	CCSDS_TDM_TRANSMITDELAY3_ID,
	CCSDS_TDM_TRANSMITDELAY4_ID,
	CCSDS_TDM_TRANSMITDELAY5_ID,
	CCSDS_TDM_RECEIVEDELAY1_ID,
	CCSDS_TDM_RECEIVEDELAY2_ID,
	CCSDS_TDM_RECEIVEDELAY3_ID,
	CCSDS_TDM_RECEIVEDELAY4_ID,
	CCSDS_TDM_RECEIVEDELAY5_ID,
	CCSDS_TDM_DATAQUALITY_ID,
	CCSDS_TDM_CORRECTIONANGLE1_ID,
	CCSDS_TDM_CORRECTIONANGLE2_ID,
	CCSDS_TDM_CORRECTIONDOPPLER_ID,
	CCSDS_TDM_CORRECTIONRANGE_ID,
	CCSDS_TDM_CORRECTIONRECEIVE_ID,
	CCSDS_TDM_CORRECTIONTRANSMIT_ID,
	CCSDS_TDM_CORRECTIONAPPLIED_ID,	
	CCSDS_TDM_ANGLE1_TIMETAG_ID,
	CCSDS_TDM_ANGLE1_MEASUREMENT_ID,
	CCSDS_TDM_ANGLE1_UNITS_ID,
	CCSDS_TDM_ANGLE2_TIMETAG_ID,
	CCSDS_TDM_ANGLE2_MEASUREMENT_ID,
	CCSDS_TDM_ANGLE2_UNITS_ID,
	CCSDS_TDM_CARRIERPOWER_TIMETAG_ID,
	CCSDS_TDM_CARRIERPOWER_MEASUREMENT_ID,
	CCSDS_TDM_CARRIERPOWER_UNITS_ID,
	CCSDS_TDM_CLOCKBIAS_TIMETAG_ID,
	CCSDS_TDM_CLOCKBIAS_MEASUREMENT_ID,
	CCSDS_TDM_CLOCKBIAS_UNITS_ID,
	CCSDS_TDM_CLOCKDRIFT_TIMETAG_ID,
	CCSDS_TDM_CLOCKDRIFT_MEASUREMENT_ID,
	CCSDS_TDM_CLOCKDRIFT_UNITS_ID,
	CCSDS_TDM_DOPPLERINSTANTANEOUS_TIMETAG_ID,
	CCSDS_TDM_DOPPLERINSTANTANEOUS_MEASUREMENT_ID,
	CCSDS_TDM_DOPPLERINSTANTANEOUS_UNITS_ID,
	CCSDS_TDM_DOPPLERINTEGRATED_TIMETAG_ID,
	CCSDS_TDM_DOPPLERINTEGRATED_MEASUREMENT_ID,
	CCSDS_TDM_DOPPLERINTEGRATED_UNITS_ID,
	CCSDS_TDM_DOR_TIMETAG_ID,
	CCSDS_TDM_DOR_MEASUREMENT_ID,
	CCSDS_TDM_DOR_UNITS_ID,
	CCSDS_TDM_PCN0_TIMETAG_ID,
	CCSDS_TDM_PCN0_MEASUREMENT_ID,
	CCSDS_TDM_PCN0_UNITS_ID,
	CCSDS_TDM_PRN0_TIMETAG_ID,
	CCSDS_TDM_PRN0_MEASUREMENT_ID,
	CCSDS_TDM_PRN0_UNITS_ID,
	CCSDS_TDM_PRESSURE_TIMETAG_ID,
	CCSDS_TDM_PRESSURE_MEASUREMENT_ID,
	CCSDS_TDM_PRESSURE_UNITS_ID,
	CCSDS_TDM_RANGE_TIMETAG_ID,
	CCSDS_TDM_RANGE_MEASUREMENT_ID,
	CCSDS_TDM_RANGE_UNITS_ID,
	CCSDS_TDM_RECEIVEFREQ_TIMETAG_ID,
	CCSDS_TDM_RECEIVEFREQ_MEASUREMENT_ID,
	CCSDS_TDM_RECEIVEFREQ_UNITS_ID,
	CCSDS_TDM_RECEIVEFREQ1_TIMETAG_ID,
	CCSDS_TDM_RECEIVEFREQ1_MEASUREMENT_ID,
	CCSDS_TDM_RECEIVEFREQ1_UNITS_ID,
	CCSDS_TDM_RECEIVEFREQ2_TIMETAG_ID,
	CCSDS_TDM_RECEIVEFREQ2_MEASUREMENT_ID,
	CCSDS_TDM_RECEIVEFREQ2_UNITS_ID,
	CCSDS_TDM_RECEIVEFREQ3_TIMETAG_ID,
	CCSDS_TDM_RECEIVEFREQ3_MEASUREMENT_ID,
	CCSDS_TDM_RECEIVEFREQ3_UNITS_ID,
	CCSDS_TDM_RECEIVEFREQ4_TIMETAG_ID,
	CCSDS_TDM_RECEIVEFREQ4_MEASUREMENT_ID,
	CCSDS_TDM_RECEIVEFREQ4_UNITS_ID,
	CCSDS_TDM_RECEIVEFREQ5_TIMETAG_ID,
	CCSDS_TDM_RECEIVEFREQ5_MEASUREMENT_ID,
	CCSDS_TDM_RECEIVEFREQ5_UNITS_ID,
	CCSDS_TDM_RHUMIDITY_TIMETAG_ID,
	CCSDS_TDM_RHUMIDITY_MEASUREMENT_ID,
	CCSDS_TDM_RHUMIDITY_UNITS_ID,
	CCSDS_TDM_STEC_TIMETAG_ID,
	CCSDS_TDM_STEC_MEASUREMENT_ID,
	CCSDS_TDM_STEC_UNITS_ID,
	CCSDS_TDM_TEMPERATURE_TIMETAG_ID,
	CCSDS_TDM_TEMPERATURE_MEASUREMENT_ID,
	CCSDS_TDM_TEMPERATURE_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQ1_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQ1_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQ1_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQ2_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQ2_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQ2_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQ3_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQ3_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQ3_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQ4_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQ4_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQ4_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQ5_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQ5_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQ5_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQRATE1_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQRATE1_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQRATE1_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQRATE2_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQRATE2_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQRATE2_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQRATE3_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQRATE3_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQRATE3_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQRATE4_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQRATE4_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQRATE4_UNITS_ID,
	CCSDS_TDM_TRANSMITFREQRATE5_TIMETAG_ID,
	CCSDS_TDM_TRANSMITFREQRATE5_MEASUREMENT_ID,
	CCSDS_TDM_TRANSMITFREQRATE5_UNITS_ID,
	CCSDS_TDM_TROPODRY_TIMETAG_ID,
	CCSDS_TDM_TROPODRY_MEASUREMENT_ID,
	CCSDS_TDM_TROPODRY_UNITS_ID,
	CCSDS_TDM_TROPOWET_TIMETAG_ID,
	CCSDS_TDM_TROPOWET_MEASUREMENT_ID,
	CCSDS_TDM_TROPOWET_UNITS_ID,
	CCSDS_TDM_VLBIDELAY_TIMETAG_ID,
	CCSDS_TDM_VLBIDELAY_MEASUREMENT_ID,
	CCSDS_TDM_VLBIDELAY_UNITS_ID,
	EndCCSDSTDMDataReps
    };
    
protected:

    static const bool CCSDS_TDM_IS_REQUIRED[EndCCSDSTDMDataReps];
    static const Gmat::ParameterType CCSDS_TDM_PARAMETER_TYPE[EndCCSDSTDMDataReps];
    static const std::string CCSDS_TDM_UNIT_DESCRIPTIONS[EndCCSDSTDMDataReps];
    static const std::string CCSDS_TDM_FILEFORMAT_DESCRIPTIONS[EndCCSDSTDMDataReps];
    
    struct ccsds_tdm_metadata
    {
	std::vector<std::string*> metadataComments;
	std::string timeSystem;
	std::string startTime;
	std::string stopTime;
	std::string *participants[5];
	std::string mode;
	std::string *path[3];
	std::string transmitBand;
	std::string receiveBand;
	Integer turnaroundNumerator;
	Integer turnaroundDenominator;
	std::string timetagRef;
	Real integrationInterval;
	std::string integrationRef;
	Real frequencyOffset;
	std::string rangeMode;
	Real rangeModulus;
	std::string rangeUnits;
	std::string angleType;
	std::string referenceFrame;
	Real *transmitDelay[5];
	Real *receiveDelay[5];
	std::string dataQuality;
	Real correctionAngle1;
	Real correctionAngle2;
	Real correctionDoppler;
	Real correctionRange;
	Real correctionReceive;
	Real correctionTransmit;
	bool correctionsApplied;
    };
    
    struct ccsds_tdm_data
    {
	std::string timeTag;
	Real measurement;
	std::string units;
    };
    
    // Iterator Pointer to the header record
    std::vector<ccsds_header*>::iterator headerVectorIndex;
    // Iterator Pointer to the metadata record
    std::vector<ccsds_tdm_metadata*>::iterator metadataVectorIndex;	
    std::vector<ccsds_tdm_data*> angle1;
    std::vector<ccsds_tdm_data*> angle2;
    std::vector<ccsds_tdm_data*> carrierPower;
    std::vector<ccsds_tdm_data*> clockBias;
    std::vector<ccsds_tdm_data*> clockDrift;
    std::vector<ccsds_tdm_data*> comment;
    std::vector<ccsds_tdm_data*> dopplerInstanteous;
    std::vector<ccsds_tdm_data*> dopplerIntegrated;
    std::vector<ccsds_tdm_data*> dor;
    std::vector<ccsds_tdm_data*> pcN0;
    std::vector<ccsds_tdm_data*> prN0;
    std::vector<ccsds_tdm_data*> pressure;
    std::vector<ccsds_tdm_data*> range;
    std::vector<ccsds_tdm_data*> receiveFrequency;
    std::vector<ccsds_tdm_data*> receiveFrequency1;
    std::vector<ccsds_tdm_data*> receiveFrequency2;
    std::vector<ccsds_tdm_data*> receiveFrequency3;
    std::vector<ccsds_tdm_data*> receiveFrequency4;
    std::vector<ccsds_tdm_data*> receiveFrequency5;
    std::vector<ccsds_tdm_data*> rHumidity;
    std::vector<ccsds_tdm_data*> stec;
    std::vector<ccsds_tdm_data*> temperature;
    std::vector<ccsds_tdm_data*> transmitFrequency1;
    std::vector<ccsds_tdm_data*> transmitFrequency2;
    std::vector<ccsds_tdm_data*> transmitFrequency3;
    std::vector<ccsds_tdm_data*> transmitFrequency4;
    std::vector<ccsds_tdm_data*> transmitFrequency5;
    std::vector<ccsds_tdm_data*> transmitFrequencyRate1;
    std::vector<ccsds_tdm_data*> transmitFrequencyRate2;
    std::vector<ccsds_tdm_data*> transmitFrequencyRate3;
    std::vector<ccsds_tdm_data*> transmitFrequencyRate4;
    std::vector<ccsds_tdm_data*> transmitFrequencyRate5;
    std::vector<ccsds_tdm_data*> tropoDry;
    std::vector<ccsds_tdm_data*> tropoWet;
    std::vector<ccsds_tdm_data*> vlbiDelay;
};

#endif	/* _CCSDSOBTYPE_HPP */

