% Generates GMAT Function and GMAT Function nested counterparts of all SystemTest scripts
%

%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Functions
%----------------------------------------

Create MatlabFunction CreateFuncSysTests;
GMAT CreateFuncSysTests.FunctionPath = './input/SystemTest/';
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
% Begin/EndScript used to force GMAT to go into command mode. Might
% not be necessary but I've included it just in case.
 
BeginScript;
EndScript;
 
% Call function
CreateFuncSysTests