% Function used: Product.gmf, BasicMath.gmf
% Function path: 
% Outputs to: 

%----------------------------------------
%---------- Spacecrafts
%----------------------------------------

Create Spacecraft DefaultSC;

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;

Create Variable OptionFlag;
Create Variable MathOutput;

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;

OptionFlag = 1

% Call function
[MathOutput] = Bug1430_Func_GFuncInsideCFlow(OptionFlag)
