%----------------------------------------
%---------- Spacecrafts
%----------------------------------------

Create Spacecraft DefaultSC;

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

% Begin/EndScript used to force GMAT to go into command mode. Might
% not be necessary but I've included it just in case.
 
BeginScript;
EndScript;

% Call function
[] = Bug1432_CheckDCsettingsInFunc
