% Created from the following script: STM_GMAT_UDMoon3rdBodyAll.m
%
% Functions used: Func_STM_GMAT_UDMoon3rdBodyAll.gmf, Func_STM_GMAT_UDMoon3rdBodyAll_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
%%GMAT reportLoc1 = './output/SystemTest/Func_STM_GMAT_UDMoon3rdBodyAll.report';
GMAT reportLoc1 = 'Bug1890-Func_STM_GMAT_UDMoon3rdBodyAll.report';
 
Create String reportLoc1_nested;
%%GMAT reportLoc1_nested = './output/SystemTest/Func_STM_GMAT_UDMoon3rdBodyAll_nested.report';
GMAT reportLoc1_nested = 'Bug1890-Func_STM_GMAT_UDMoon3rdBodyAll_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
% Begin/EndScript used to force GMAT to go into command mode. Might
% not be necessary but I've included it just in case.
 
BeginScript;
EndScript;
 
% Call function
Func_STM_GMAT_UDMoon3rdBodyAll(reportLoc1)
Func_STM_GMAT_UDMoon3rdBodyAll_nested(reportLoc1_nested)
