% $Id: Func_CoordSysInputTests.script,v 1.2 2008/05/02 19:05:36 edove Exp $

% Func_CoordSysInputTests - This script tests to make sure 
%
% Function used: Func_CoordSysInputTests.gmf, Func_CoordSysInputTests_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/ 

%----------------------------------------
%---------- Spacecrafts
%----------------------------------------

Create Spacecraft DefaultSC;

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;

%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------

Create String reportLoc;
%%GMAT reportLoc = './output/SystemTest/Func_CoordSysInputTests.report';
GMAT reportLoc = 'Bug1386-Func_CoordSysInputTests.report';

Create String reportLoc_nested;
%%GMAT reportLoc_nested = './output/SystemTest/Func_CoordSysInputTests_nested.report';
GMAT reportLoc_nested = 'Bug1386-Func_CoordSysInputTests_nested.report';

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;

% Call function
Bug1386_Func_CoordSysInputTests(reportLoc);
Bug1386_Func_CoordSysInputTests_nested(reportLoc_nested);
