%General Mission Analysis Tool(GMAT) Script
%Created: 2013-05-06 11:55:27


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
DefaultSC.DateFormat = TAIModJulian;
DefaultSC.Epoch = '21545';
DefaultSC.CoordinateSystem = EarthMJ2000Eq;
DefaultSC.DisplayStateType = Cartesian;
DefaultSC.X = 7100;
DefaultSC.Y = 0;
DefaultSC.Z = 1300;
DefaultSC.VX = 0;
DefaultSC.VY = 7.35;
DefaultSC.VZ = 1;
DefaultSC.DryMass = 850;
DefaultSC.Cd = 2.2;
DefaultSC.Cr = 1.8;
DefaultSC.DragArea = 15;
DefaultSC.SRPArea = 1;
DefaultSC.NAIFId = -123456789;
DefaultSC.NAIFIdReferenceFrame = -123456789;
DefaultSC.Id = 'SatId';
DefaultSC.Attitude = CoordinateSystemFixed;
DefaultSC.ModelFile = 'C:/Projects/GmatDev/application/data/vehicle/models/aura.3ds';
DefaultSC.ModelOffsetX = 0;
DefaultSC.ModelOffsetY = 0;
DefaultSC.ModelOffsetZ = 0;
DefaultSC.ModelRotationX = 0;
DefaultSC.ModelRotationY = 0;
DefaultSC.ModelRotationZ = 0;
DefaultSC.ModelScale = 3;
DefaultSC.AttitudeDisplayStateType = 'Quaternion';
DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
DefaultSC.EulerAngleSequence = '321';

%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.EarthTideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-012;
%%DefaultProp.MinStep = 0.001;
%%DefaultProp.MaxStep = 2700;
DefaultProp.MinStep = 60.0;
DefaultProp.MaxStep = 60.0;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn DefaultIB;
DefaultIB.CoordinateSystem = Local;
DefaultIB.Origin = Earth;
DefaultIB.Axes = VNB;
DefaultIB.Element1 = 0;
DefaultIB.Element2 = 0;
DefaultIB.Element3 = 0;
DefaultIB.DecrementMass = false;
DefaultIB.Isp = 300;
DefaultIB.GravitationalAccel = 9.810000000000001;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
DefaultOrbitView.SolverIterations = Current;
DefaultOrbitView.UpperLeft = [ 0.4979166666666667 0 ];
DefaultOrbitView.Size = [ 0.4979166666666667 0.9925650557620818 ];
DefaultOrbitView.RelativeZOrder = 31;
DefaultOrbitView.Maximized = false;
DefaultOrbitView.Add = {DefaultSC, Earth};
DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.DrawObject = [ true true ];
DefaultOrbitView.OrbitColor = [ 255 32768 ];
DefaultOrbitView.TargetColor = [ 8421440 0 ];
DefaultOrbitView.DataCollectFrequency = 1;
DefaultOrbitView.UpdatePlotFrequency = 50;
DefaultOrbitView.NumPointsToRedraw = 0;
DefaultOrbitView.ShowPlot = true;
DefaultOrbitView.ViewPointReference = Earth;
DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
DefaultOrbitView.ViewDirection = Earth;
DefaultOrbitView.ViewScaleFactor = 1;
DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.ViewUpAxis = Z;
DefaultOrbitView.EclipticPlane = Off;
DefaultOrbitView.XYPlane = On;
DefaultOrbitView.WireFrame = Off;
DefaultOrbitView.Axes = On;
DefaultOrbitView.Grid = Off;
DefaultOrbitView.SunLine = Off;
DefaultOrbitView.UseInitialView = On;
DefaultOrbitView.StarCount = 7000;
DefaultOrbitView.EnableStars = On;
DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
DefaultGroundTrackPlot.SolverIterations = Current;
DefaultGroundTrackPlot.UpperLeft = [ 0 0 ];
DefaultGroundTrackPlot.Size = [ 0.4979166666666667 0.9925650557620818 ];
DefaultGroundTrackPlot.RelativeZOrder = 33;
DefaultGroundTrackPlot.Maximized = false;
DefaultGroundTrackPlot.Add = {DefaultSC, Earth};
DefaultGroundTrackPlot.DataCollectFrequency = 1;
DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
DefaultGroundTrackPlot.NumPointsToRedraw = 0;
DefaultGroundTrackPlot.ShowPlot = true;
DefaultGroundTrackPlot.CentralBody = Earth;
DefaultGroundTrackPlot.TextureMap = 'C:/Projects/GmatDev/application/data/graphics/texture/ModifiedBlueMarble.jpg';

Create ReportFile ReportFile1;
ReportFile1.SolverIterations = Current;
ReportFile1.UpperLeft = [ 0 0 ];
ReportFile1.Size = [ 0 0 ];
ReportFile1.RelativeZOrder = 0;
ReportFile1.Maximized = false;
ReportFile1.Filename = 'EPHEM_Validation_PARSING_ERROR.txt';
ReportFile1.Precision = 16;
ReportFile1.Add = {DefaultSC.A1ModJulian, DefaultSC.EarthMJ2000Eq.X};
ReportFile1.WriteHeaders = true;
ReportFile1.LeftJustify = On;
ReportFile1.ZeroFill = Off;
ReportFile1.ColumnWidth = 20;
ReportFile1.WriteReport = true;

Create EphemerisFile EphemCCSDS;
EphemCCSDS.UpperLeft = [ 0 0 ];
EphemCCSDS.Size = [ 0 0 ];
EphemCCSDS.RelativeZOrder = 0;
EphemCCSDS.Maximized = false;
EphemCCSDS.Spacecraft = DefaultSC;
EphemCCSDS.Filename = 'EPHEM_Validation_CCSDS.eph';
EphemCCSDS.FileFormat = CCSDS-OEM;
EphemCCSDS.EpochFormat = UTCGregorian; %% Error
EphemCCSDS.InitialEpoch = InitialSpacecraftEpoch;
EphemCCSDS.FinalEpoch = FinalSpacecraftEpoch;
EphemCCSDS.StepSize = IntegratorSteps;
EphemCCSDS.InterpolationOrder = 7;
%EphemCCSDS.CoordinateSystem = EarthMJ2000Eq;
EphemCCSDS.CoordinateSystem = EarthFixed;
EphemCCSDS.WriteEphemeris = true;

Create EphemerisFile EphemSPK;
EphemSPK.UpperLeft = [ 0 0 ];
EphemSPK.Size = [ 0 0 ];
EphemSPK.RelativeZOrder = 0;
EphemSPK.Maximized = false;
EphemSPK.Spacecraft = DefaultSC;
EphemSPK.Filename = 'EPHEM_Validation_SPK.bsp';
EphemSPK.FileFormat = SPK;
EphemSPK.EpochFormat = UTCGregorian;
EphemSPK.InitialEpoch = InitialSpacecraftEpoch;
EphemSPK.FinalEpoch = FinalSpacecraftEpoch;
EphemSPK.StepSize = 60;
EphemSPK.InterpolationOrder = 7;
%EphemSPK.CoordinateSystem = EarthMJ2000Eq;
EphemSPK.CoordinateSystem = EarthFixed; %% Not allowed in validation
EphemSPK.WriteEphemeris = true;

Create EphemerisFile EphemCODE500;
EphemCODE500.UpperLeft = [ 0 0 ];
EphemCODE500.Size = [ 0 0 ];
EphemCODE500.RelativeZOrder = 0;
EphemCODE500.Maximized = false;
EphemCODE500.Spacecraft = DefaultSC;
EphemCODE500.Filename = 'EPHEM_All_3_Types_Code500.eph';
EphemCODE500.FileFormat = Code-500;
EphemCODE500.EpochFormat = UTCGregorian;
EphemCODE500.InitialEpoch = InitialSpacecraftEpoch;
EphemCODE500.FinalEpoch = FinalSpacecraftEpoch;
EphemCODE500.StepSize = 60;
EphemCODE500.InterpolationOrder = 7;
%EphemCODE500.CoordinateSystem = EarthMJ2000Eq;
EphemCODE500.CoordinateSystem = EarthFixed; %% Not allowed in validation
EphemCODE500.WriteEphemeris = true;

Create EphemerisFile EphemCODE500_A;
EphemCODE500_A.FileFormat = Code-500;
EphemCODE500_A.StepSize = IntegratorSteps;

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(DefaultSC) {DefaultSC.ElapsedSecs = 12000.0};
