% Created from the following script: UDCB_GMAT_Asteroid2Body.m
%
% Functions used: Func_UDCB_GMAT_Asteroid2Body.gmf, Func_UDCB_GMAT_Asteroid2Body_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
%%GMAT reportLoc1 = './output/SystemTest/Func_UDCB_GMAT_Asteroid2Body.report';
GMAT reportLoc1 = 'Bug1890-Func_UDCB_GMAT_Asteroid2Body.report';
 
Create String reportLoc1_nested;
%%GMAT reportLoc1_nested = './output/SystemTest/Func_UDCB_GMAT_Asteroid2Body_nested.report';
GMAT reportLoc1_nested = 'Bug1890-Func_UDCB_GMAT_Asteroid2Body_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
 
% Call function
Func_UDCB_GMAT_Asteroid2Body(reportLoc1)
Func_UDCB_GMAT_Asteroid2Body_nested(reportLoc1_nested)
