% Created from the following script: SPK_GMAT_CometBorrelly.m
%
% Functions used: Func_SPK_GMAT_CometBorrelly.gmf, Func_SPK_GMAT_CometBorrelly_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
%%%GMAT reportLoc1 = './output/SystemTest/Func_SPK_GMAT_CometBorrelly.report';
GMAT reportLoc1 = 'Bug1889-Func_SPK_GMAT_CometBorrelly.report';
 
Create String reportLoc1_nested;
%%GMAT reportLoc1_nested = './output/SystemTest/Func_SPK_GMAT_CometBorrelly_nested.report';
GMAT reportLoc1_nested = 'Bug1889-Func_SPK_GMAT_CometBorrelly_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
 
% Call function
Func_SPK_GMAT_CometBorrelly(reportLoc1)
Func_SPK_GMAT_CometBorrelly_nested(reportLoc1_nested)
