%$Id$
% Created from the following script: TargeterCheck.m
%
% Functions used: Func_TargeterCheck.gmf, Func_TargeterCheck_nested.gmf
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
GMAT reportLoc1 = 'Func_TargeterCheck.report';
 
Create String reportLoc1_nested;
GMAT reportLoc1_nested = 'Func_TargeterCheck_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
BeginMissionSequence;
 
% Call function
Func_TargeterCheck(reportLoc1)
Func_TargeterCheck_nested(reportLoc1_nested)
