% $Id: Func_AssigningWholeObjects.script,v 1.2 2008/05/02 19:05:35 edove Exp $

% Func_AssigningWholeObjects - This script tests to make sure 
%
% Function used: Func_AssigningWholeObjects.gmf, Func_AssigningWholeObjects_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/ 

%----------------------------------------
%---------- Spacecrafts
%----------------------------------------

Create Spacecraft DefaultSC;

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;

% Call functions
Func_AssigningWholeObjects;
Func_AssigningWholeObjects_nested;
