%$Id$
% Created from the following script: TargeterNesting.m
%
% Functions used: Func_TargeterNesting.gmf, Func_TargeterNesting_nested.gmf
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
GMAT reportLoc1 = 'Func_TargeterNesting.report';
 
Create String reportLoc1_nested;
GMAT reportLoc1_nested = 'Func_TargeterNesting_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
BeginMissionSequence;
 
% Call function
Func_TargeterNesting(reportLoc1)
Func_TargeterNesting_nested(reportLoc1_nested)
