 function [FormationState] = MultiInput1Output(allCartStates, refKepState, ...
         initialEpoch, refSatIndex, includeRefInOpt, objStepSize, ...
         nominalSideLength, roiLowerBound, numRevs, closeApproachLimit, ...
         conStepSizeCA, conScaleFactorCA, outputStateType, objScaleFactor, ...
         posScaleFactor, velScaleFactor)

FormationState(1:6,1) = allCartStates(1:6);
FormationState(1:6,2) = allCartStates(7:12);
FormationState(1:6,3) = allCartStates(13:18);
FormationState(1:6,4) = allCartStates(19:24);

%%%FormationState = reshape(allCartStates, 6, 4);

