# $Id: Makefile 7882 2011-06-14 18:22:44Z tdnguye2 $
# Root level makefile 
#
# This file calls make on the src folder.

all: 
	cd src; make all

rebuild: 
	cd src; make clean; make all

clean:
	cd src; make clean
