[COMMAND1]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/AllForces4by4JR_10Day.ElapsedDays <= 10\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND2]
Command1=Disabled\/SPACE\/Step\/SPACE\/AllForces4by4JR_10Day\/SPACE\/\/SPACE\/
[COMMAND3]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND4]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/Earth00_10Day.ElapsedDays <= 10\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[FORMAT_SECTION]
Position=68
ProjectDir=C:\GMAT_results\TruthFiles\FF\PerformanceTests\
ProjectType=1
NumLines=29
0CWObjectList0=225
0CWObjectListLast0=199
0CWObjectList1=225
0CWObjectListLast1=199
0CWObjectList2=-1
0CWObjectListLast2=-1
0CWObjectList3=520
0CWObjectListLast3=460
1CWObjectList0=228
1CWObjectListLast0=199
1CWObjectList1=228
1CWObjectListLast1=199
1CWObjectList2=-1
1CWObjectListLast2=-1
1CWObjectList3=530
1CWObjectListLast3=460
2CWObjectList0=228
2CWObjectListLast0=199
2CWObjectList1=228
2CWObjectListLast1=199
2CWObjectList2=-1
2CWObjectListLast2=-1
2CWObjectList3=530
2CWObjectListLast3=460
3CWObjectList0=231
3CWObjectListLast0=201
3CWObjectList1=-1
3CWObjectListLast1=-1
3CWObjectList2=154
3CWObjectListLast2=134
3CWObjectList3=587
3CWObjectListLast3=509
4CWObjectList0=83
4CWObjectListLast0=72
4CWObjectList1=222
4CWObjectListLast1=193
4CWObjectList2=333
4CWObjectListLast2=289
4CWObjectList3=333
4CWObjectListLast3=289
CWMDS0=69
CWMDSLast0=61
CWMDS1=335
CWMDSLast1=295
CWMDS2=355
CWMDSLast2=312
CWMDS3=169
CWMDSLast3=148
ActivePage=0
MDSRecord=7
[COMMAND5]
Command1=Disabled\/SPACE\/Step\/SPACE\/Earth00_10Day\/SPACE\/\/SPACE\/
[COMMAND6]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND7]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/Earth00JRDrag_10Day.ElapsedDays <= 10\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND8]
Command1=Disabled\/SPACE\/Step\/SPACE\/Earth00JRDrag_10Day\/SPACE\/\/SPACE\/
[COMMAND9]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND10]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/Earth20by20_10Day.ElapsedDays <= 10\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND11]
Command1=Disabled\/SPACE\/Step\/SPACE\/Earth20by20_10Day\/SPACE\/\/SPACE\/
[COMMAND12]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND13]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/EarthJ2_10Day.ElapsedDays <= 10\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND14]
Command1=Disabled\/SPACE\/Step\/SPACE\/EarthJ2_10Day\/SPACE\/\/SPACE\/
[COMMAND15]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND16]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/SEMPointMass10Day.ElapsedDays <= 10\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND17]
Command1=Disabled\/SPACE\/Step\/SPACE\/SEMPointMass10Day\/SPACE\/\/SPACE\/
[COMMAND18]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND19]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/SRP_ESMPointMass_10Day.ElapsedDays <= 10\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND20]
Command1=Disabled\/SPACE\/Step\/SPACE\/SRP_ESMPointMass_10Day\/SPACE\/\/SPACE\/
[COMMAND21]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND22]
Command1=Enabled\/SPACE\/Step\/SPACE\/Earth00_10Day\/SPACE\/\/SPACE\/
[COMMAND23]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND24]
Command1=Enabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/Earth00_10Day.ElapsedDays <= 10\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND25]
Command1=Enabled\/SPACE\/Report\/SPACE\/Earth00_10Day.ElapsedMinutes<15,9>, Earth00_10Day.X<15,9>, Earth00_10Day.Y<15,9>, Earth00_10Day.Z<15,9>, Earth00_10Day.VX<15,9>, Earth00_10Day.VY<15,9>, Earth00_10Day.VZ<15,9>\/Delimit\/Earth00_10Day.ElapsedMinutes<15,9>\/Delimit\/Earth00_10Day.X<15,9>\/Delimit\/Earth00_10Day.Y<15,9>\/Delimit\/Earth00_10Day.Z<15,9>\/Delimit\/Earth00_10Day.VX<15,9>\/Delimit\/Earth00_10Day.VY<15,9>\/Delimit\/Earth00_10Day.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/Earth00_10Day.report\/SPACE\/\/SPACE\/
[COMMAND26]
Command1=Enabled\/SPACE\/Step\/SPACE\/Earth00_10Day\/SPACE\/\/SPACE\/
[CopyOfISS]
EphemFileType=Unknown
UseEphem=0
[COMMAND27]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND28]
Command1=Enabled\/SPACE\/Step\/SPACE\/Molniya\/SPACE\/\/SPACE\/
[COMMAND29]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND30]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND31]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/ISS.ElapsedDays <= 1.007\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND32]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/CountTime = 0\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND33]
Command1=Disabled\/SPACE\/Report\/SPACE\/ISS.ElapsedDays<15,9>, ISS.X<15,9>, ISS.Y<15,9>, ISS.Z<15,9>, ISS.VX<15,9>, ISS.VY<15,9>, ISS.VZ<15,9>, CountTime<15,9>, ISS.ElapsedSeconds<15,9>\/Delimit\/ISS.ElapsedDays<15,9>\/Delimit\/ISS.X<15,9>\/Delimit\/ISS.Y<15,9>\/Delimit\/ISS.Z<15,9>\/Delimit\/ISS.VX<15,9>\/Delimit\/ISS.VY<15,9>\/Delimit\/ISS.VZ<15,9>\/Delimit\/CountTime<15,9>\/Delimit\/ISS.ElapsedSeconds<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0.Report\/SPACE\/\/SPACE\/
[COMMAND34]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND35]
Command1=Disabled\/SPACE\/Step\/SPACE\/ISS\/SPACE\/\/SPACE\/
[COMMAND36]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/Dummy = ( ISS.ElapsedSeconds )\/Delimit\/Variable\/Operator\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND37]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/CountTime > 0 and Flag = 0\/Delimit\/Variable\/Operator\/Number\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND38]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/Flag = ( 1 )\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND39]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/SS = ( Dummy )\/Delimit\/Variable\/Operator\/Variable\/Operator\/Object Parameter\/SPACE\/\/SPACE\/
[COMMAND40]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND41]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/CountTime = 0\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND42]
Command1=Disabled\/SPACE\/Report\/SPACE\/ISS.ElapsedDays<15,9>, ISS.X<15,9>, ISS.Y<15,9>, ISS.Z<15,9>, ISS.VX<15,9>, ISS.VY<15,9>, ISS.VZ<15,9>, CountTime<15,9>, ISS.ElapsedSeconds<15,9>\/Delimit\/ISS.ElapsedDays<15,9>\/Delimit\/ISS.X<15,9>\/Delimit\/ISS.Y<15,9>\/Delimit\/ISS.Z<15,9>\/Delimit\/ISS.VX<15,9>\/Delimit\/ISS.VY<15,9>\/Delimit\/ISS.VZ<15,9>\/Delimit\/CountTime<15,9>\/Delimit\/ISS.ElapsedSeconds<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0.Report\/SPACE\/\/SPACE\/
[COMMAND43]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND44]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/ReportTime = ( CountTime * SS )\/Delimit\/Variable\/Operator\/Variable\/Operator\/Variable\/SPACE\/\/SPACE\/
[COMMAND45]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/ReportTime = 600\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND46]
Command1=Disabled\/SPACE\/Report\/SPACE\/ISS.ElapsedDays<15,9>, ISS.X<15,9>, ISS.Y<15,9>, ISS.Z<15,9>, ISS.VX<15,9>, ISS.VY<15,9>, ISS.VZ<15,9>, CountTime<15,9>, ISS.ElapsedSeconds<15,9>\/Delimit\/ISS.ElapsedDays<15,9>\/Delimit\/ISS.X<15,9>\/Delimit\/ISS.Y<15,9>\/Delimit\/ISS.Z<15,9>\/Delimit\/ISS.VX<15,9>\/Delimit\/ISS.VY<15,9>\/Delimit\/ISS.VZ<15,9>\/Delimit\/CountTime<15,9>\/Delimit\/ISS.ElapsedSeconds<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0.Report\/SPACE\/\/SPACE\/
[COMMAND47]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/CountTime = ( 0 )\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND48]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND49]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/CountTime = ( CountTime + 1 )\/Delimit\/Variable\/Operator\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND50]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND51]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/CopyOfISS.ElapsedDays < 1\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND52]
Command1=Disabled\/SPACE\/View\/SPACE\/CopyOfISS\/SPACE\/\/SPACE\/
[COMMAND53]
Command1=Disabled\/SPACE\/Report\/SPACE\/CopyOfISS.ElapsedMinutes<15,9>, CopyOfISS.X<15,9>, CopyOfISS.Y<15,9>, CopyOfISS.Z<15,9>, CopyOfISS.VX<15,9>, CopyOfISS.VY<15,9>, CopyOfISS.VZ<15,9>\/Delimit\/CopyOfISS.ElapsedMinutes<15,9>\/Delimit\/CopyOfISS.X<15,9>\/Delimit\/CopyOfISS.Y<15,9>\/Delimit\/CopyOfISS.Z<15,9>\/Delimit\/CopyOfISS.VX<15,9>\/Delimit\/CopyOfISS.VY<15,9>\/Delimit\/CopyOfISS.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0_check.Report\/SPACE\/\/SPACE\/
[COMMAND54]
Command1=Disabled\/SPACE\/Step\/SPACE\/CopyOfISS to (CopyOfISS.ElapsedMinutes < 10)\/SPACE\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND55]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[GEO]
EphemFileType=Unknown
UseEphem=0
[GPS]
EphemFileType=Unknown
UseEphem=0
[SunSync]
EphemFileType=Unknown
UseEphem=0
[Molniya]
EphemFileType=Unknown
UseEphem=0
[AllForces4by4JR_10Day]
EphemFileType=Unknown
UseEphem=0
[Earth00_10Day]
EphemFileType=Unknown
UseEphem=0
[Earth00JRDrag_10Day]
EphemFileType=Unknown
UseEphem=0
[Earth20by20_10Day]
EphemFileType=Unknown
UseEphem=0
[SEMPointMass10Day]
EphemFileType=Unknown
UseEphem=0
[SRP_ESMPointMass_10Day]
EphemFileType=Unknown
UseEphem=0
[EarthJ2_10Day]
EphemFileType=Unknown
UseEphem=0
[START_SECTION]
Start1=Enabled\/SPACE\/Spacecraft\/SPACE\/AllForces4by4JR_10Day\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start2=Enabled\/SPACE\/Spacecraft\/SPACE\/Earth00_10Day\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start3=Enabled\/SPACE\/Spacecraft\/SPACE\/Earth00JRDrag_10Day\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start4=Enabled\/SPACE\/Spacecraft\/SPACE\/Earth20by20_10Day\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start5=Enabled\/SPACE\/Spacecraft\/SPACE\/EarthJ2_10Day\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start6=Enabled\/SPACE\/Spacecraft\/SPACE\/SEMPointMass10Day\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start7=Enabled\/SPACE\/Spacecraft\/SPACE\/SRP_ESMPointMass_10Day\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
[COMMAND_SECTION]
Number_Commands=21
