[COMMAND1]
Command1=Enabled\/SPACE\/FreeForm\/SPACE\/Universe settings\/SPACE\/FreeformScript2\/SPACE\/\/SPACE\/
[COMMAND2]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_2Body Output\/SPACE\/FreeformScript4\/SPACE\/\/SPACE\/
[COMMAND3]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_2Body noOutput\/SPACE\/FreeformScript5\/SPACE\/\/SPACE\/
[COMMAND4]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_AllPlanets Output\/SPACE\/FreeformScript6\/SPACE\/\/SPACE\/
[FORMAT_SECTION]
Position=233
ProjectDir=C:\GMAT_results\TruthFiles\FF\Performance\
ProjectType=1
NumLines=77
0CWObjectList0=223
0CWObjectListLast0=74
0CWObjectList1=478
0CWObjectListLast1=159
0CWObjectList2=-1
0CWObjectListLast2=-1
0CWObjectList3=269
0CWObjectListLast3=89
1CWObjectList0=228
1CWObjectListLast0=199
1CWObjectList1=228
1CWObjectListLast1=199
1CWObjectList2=-1
1CWObjectListLast2=-1
1CWObjectList3=530
1CWObjectListLast3=460
2CWObjectList0=228
2CWObjectListLast0=199
2CWObjectList1=228
2CWObjectListLast1=199
2CWObjectList2=-1
2CWObjectListLast2=-1
2CWObjectList3=530
2CWObjectListLast3=460
3CWObjectList0=231
3CWObjectListLast0=201
3CWObjectList1=-1
3CWObjectListLast1=-1
3CWObjectList2=154
3CWObjectListLast2=134
3CWObjectList3=587
3CWObjectListLast3=509
4CWObjectList0=83
4CWObjectListLast0=72
4CWObjectList1=222
4CWObjectListLast1=193
4CWObjectList2=333
4CWObjectListLast2=289
4CWObjectList3=333
4CWObjectListLast3=289
CWMDS0=69
CWMDSLast0=61
CWMDS1=335
CWMDSLast1=295
CWMDS2=355
CWMDSLast2=312
CWMDS3=169
CWMDSLast3=148
ActivePage=1
MDSRecord=1
[COMMAND5]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_AllPlanets noOutput\/SPACE\/FreeformScript53\/SPACE\/\/SPACE\/
[COMMAND6]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_NSG Output\/SPACE\/FreeformScript8\/SPACE\/\/SPACE\/
[COMMAND7]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_NSG noOutput\/SPACE\/FreeformScript51\/SPACE\/\/SPACE\/
[COMMAND8]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_Drag Output\/SPACE\/FreeformScript10\/SPACE\/\/SPACE\/
[COMMAND9]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_Drag noOutput\/SPACE\/FreeformScript49\/SPACE\/\/SPACE\/
[COMMAND10]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_SRP Output\/SPACE\/FreeformScript12\/SPACE\/\/SPACE\/
[COMMAND11]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate ISS_SRP noOutput\/SPACE\/FreeformScript47\/SPACE\/\/SPACE\/
[COMMAND12]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_2Body Output\/SPACE\/FreeformScript14\/SPACE\/\/SPACE\/
[COMMAND13]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_2Body noOutput\/SPACE\/FreeformScript45\/SPACE\/\/SPACE\/
[COMMAND14]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_AllPlanets Output\/SPACE\/FreeformScript16\/SPACE\/\/SPACE\/
[COMMAND15]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_AllPlanets noOutput\/SPACE\/FreeformScript43\/SPACE\/\/SPACE\/
[COMMAND16]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_NSG Output\/SPACE\/FreeformScript18\/SPACE\/\/SPACE\/
[COMMAND17]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_NSG noOutput\/SPACE\/FreeformScript41\/SPACE\/\/SPACE\/
[COMMAND18]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_Drag Output\/SPACE\/FreeformScript20\/SPACE\/\/SPACE\/
[COMMAND19]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_Drag noOutput\/SPACE\/FreeformScript35\/SPACE\/\/SPACE\/
[COMMAND20]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_SRP Output\/SPACE\/FreeformScript22\/SPACE\/\/SPACE\/
[COMMAND21]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GEO_SRP noOutput\/SPACE\/FreeformScript27\/SPACE\/\/SPACE\/
[COMMAND22]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_2Body Output\/SPACE\/FreeformScript24\/SPACE\/\/SPACE\/
[COMMAND23]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_2Body noOutput\/SPACE\/FreeformScript21\/SPACE\/\/SPACE\/
[COMMAND24]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_AllPlanets Output\/SPACE\/FreeformScript26\/SPACE\/\/SPACE\/
[COMMAND25]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_AllPlanets noOutput\/SPACE\/FreeformScript25\/SPACE\/\/SPACE\/
[COMMAND26]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_NSG Output\/SPACE\/FreeformScript28\/SPACE\/\/SPACE\/
[COMMAND27]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_NSG noOutput\/SPACE\/FreeformScript23\/SPACE\/\/SPACE\/
[COMMAND28]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_Drag Output\/SPACE\/FreeformScript30\/SPACE\/\/SPACE\/
[COMMAND29]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_Drag noOutput\/SPACE\/FreeformScript19\/SPACE\/\/SPACE\/
[COMMAND30]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_SRP Output\/SPACE\/FreeformScript32\/SPACE\/\/SPACE\/
[COMMAND31]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate GPS_SRP noOutput\/SPACE\/FreeformScript29\/SPACE\/\/SPACE\/
[COMMAND32]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_2Body Output\/SPACE\/FreeformScript34\/SPACE\/\/SPACE\/
[COMMAND33]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_2Body noOutput\/SPACE\/FreeformScript17\/SPACE\/\/SPACE\/
[COMMAND34]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_AllPlanets Output\/SPACE\/FreeformScript36\/SPACE\/\/SPACE\/
[COMMAND35]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_AllPlanets noOutput\/SPACE\/FreeformScript15\/SPACE\/\/SPACE\/
[COMMAND36]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_NSG Output\/SPACE\/FreeformScript38\/SPACE\/\/SPACE\/
[COMMAND37]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_NSG noOutput\/SPACE\/FreeformScript31\/SPACE\/\/SPACE\/
[COMMAND38]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_Drag Output\/SPACE\/FreeformScript40\/SPACE\/\/SPACE\/
[COMMAND39]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_Drag noOutput\/SPACE\/FreeformScript13\/SPACE\/\/SPACE\/
[COMMAND40]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_SRP Output\/SPACE\/FreeformScript42\/SPACE\/\/SPACE\/
[COMMAND41]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate Molniya_SRP noOutput\/SPACE\/FreeformScript9\/SPACE\/\/SPACE\/
[COMMAND42]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_2Body Output\/SPACE\/FreeformScript44\/SPACE\/\/SPACE\/
[COMMAND43]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_2Body noOutput\/SPACE\/FreeformScript11\/SPACE\/\/SPACE\/
[COMMAND44]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_AllPlanets Output\/SPACE\/FreeformScript46\/SPACE\/\/SPACE\/
[COMMAND45]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_AllPlanets noOutput\/SPACE\/FreeformScript33\/SPACE\/\/SPACE\/
[COMMAND46]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_NSG Output\/SPACE\/FreeformScript48\/SPACE\/\/SPACE\/
[COMMAND47]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_NSG noOutput\/SPACE\/FreeformScript7\/SPACE\/\/SPACE\/
[COMMAND48]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_Drag Output\/SPACE\/FreeformScript50\/SPACE\/\/SPACE\/
[COMMAND49]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_Drag noOutput\/SPACE\/FreeformScript37\/SPACE\/\/SPACE\/
[COMMAND50]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_SRP Output\/SPACE\/FreeformScript52\/SPACE\/\/SPACE\/
[COMMAND51]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_SRP noOutput\/SPACE\/FreeformScript39\/SPACE\/\/SPACE\/
[COMMAND52]
Command1=Disabled\/SPACE\/FreeForm\/SPACE\/Propagate SunSync_SRP noOutput\/SPACE\/FreeformScript39\/SPACE\/\/SPACE\/
[COMMAND53]
Command1=Disabled\/SPACE\/Report\/SPACE\/CopyOfISS.ElapsedMinutes<15,9>, CopyOfISS.X<15,9>, CopyOfISS.Y<15,9>, CopyOfISS.Z<15,9>, CopyOfISS.VX<15,9>, CopyOfISS.VY<15,9>, CopyOfISS.VZ<15,9>\/Delimit\/CopyOfISS.ElapsedMinutes<15,9>\/Delimit\/CopyOfISS.X<15,9>\/Delimit\/CopyOfISS.Y<15,9>\/Delimit\/CopyOfISS.Z<15,9>\/Delimit\/CopyOfISS.VX<15,9>\/Delimit\/CopyOfISS.VY<15,9>\/Delimit\/CopyOfISS.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0_check.Report\/SPACE\/\/SPACE\/
[COMMAND54]
Command1=Disabled\/SPACE\/Step\/SPACE\/CopyOfISS to (CopyOfISS.ElapsedMinutes < 10)\/SPACE\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND55]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[ISS]
EphemFileType=Unknown
UseEphem=0
[GEO]
EphemFileType=Unknown
UseEphem=0
[GPS]
EphemFileType=Unknown
UseEphem=0
[SunSync]
EphemFileType=Unknown
UseEphem=0
[Molniya]
EphemFileType=Unknown
UseEphem=0
[GEO_2Body]
EphemFileType=Unknown
UseEphem=0
[GPS_2Body]
EphemFileType=Unknown
UseEphem=0
[SunSync_2Body]
EphemFileType=Unknown
UseEphem=0
[Molniya_2Body]
EphemFileType=Unknown
UseEphem=0
[ISS_2Body]
EphemFileType=Unknown
UseEphem=0
[FreeformScript3]
FreeFormLine1=\/SPACE\/Create Spacecraft ISS_JGM2 using ISS_2Body_prop;\/END\/
FreeFormLine2=\/SPACE\/ISS_JGM2 = ISS_2Body;\/END\/
FreeFormLine3=\/SPACE\/\/END\/
FreeFormLine4=\/SPACE\/ISS_JGM2.X = 0;\/END\/
FreeFormLine5=\/SPACE\/ISS_JGM2_FM.FieldOrder = 5;\/END\/
FreeFormLine6=\/SPACE\/\/END\/
FreeFormLine7=\/SPACE\/Report ISS_2Body.ElapsedMinutes<15,9>, ISS_2Body.X<15,9>, ISS_2Body.Y<15,9>, ISS_2Body.Z<15,9>, ISS_2Body.VX<15,9>, ISS_2Body.VY<15,9>, ISS_2Body.VZ<15,9> to "Test_ISS2Body.report";\/END\/
FreeFormLine8=\/SPACE\/Report ISS_JGM2.ElapsedMinutes<15,9>, ISS_JGM2.X<15,9>, ISS_JGM2.Y<15,9>, ISS_JGM2.Z<15,9>, ISS_JGM2.VX<15,9>, ISS_JGM2.VY<15,9>, ISS_JGM2.VZ<15,9> to "Test_ISSJGM2.report";\/END\/
FreeFormLine9=\/SPACE\/\/END\/
FreeFormLine10=\/SPACE\/Put ISS_JGM2 to "ISS_JGM2.State";\/END\/
[GEO_NSG]
EphemFileType=Unknown
UseEphem=0
[GEO_Drag]
EphemFileType=Unknown
UseEphem=0
[GEO_SRP]
EphemFileType=Unknown
UseEphem=0
[GPS_NSG]
EphemFileType=Unknown
UseEphem=0
[GPS_Drag]
EphemFileType=Unknown
UseEphem=0
[GPS_SRP]
EphemFileType=Unknown
UseEphem=0
[GPS_AllPlanets]
EphemFileType=Unknown
UseEphem=0
[SunSync_NSG]
EphemFileType=Unknown
UseEphem=0
[SunSync_Drag]
EphemFileType=Unknown
UseEphem=0
[SunSync_AllPlanets]
EphemFileType=Unknown
UseEphem=0
[SunSync_SRP]
EphemFileType=Unknown
UseEphem=0
[Molniya_SRP]
EphemFileType=Unknown
UseEphem=0
[Molniya_AllPlanets]
EphemFileType=Unknown
UseEphem=0
[Molniya_NSG]
EphemFileType=Unknown
UseEphem=0
[Molniya_Drag]
EphemFileType=Unknown
UseEphem=0
[ISS_NSG]
EphemFileType=Unknown
UseEphem=0
[ISS_Drag]
EphemFileType=Unknown
UseEphem=0
[ISS_SRP]
EphemFileType=Unknown
UseEphem=0
[ISS_AllPlanets]
EphemFileType=Unknown
UseEphem=0
[GEO_AllPlanets]
EphemFileType=Unknown
UseEphem=0
[START_SECTION]
Start1=Enabled\/SPACE\/Spacecraft\/SPACE\/ISS_2Body\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start2=Enabled\/SPACE\/Spacecraft\/SPACE\/ISS_AllPlanets\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start3=Enabled\/SPACE\/Spacecraft\/SPACE\/ISS_NSG\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start4=Enabled\/SPACE\/Spacecraft\/SPACE\/ISS_SRP\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start5=Enabled\/SPACE\/Spacecraft\/SPACE\/ISS_Drag\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start6=Enabled\/SPACE\/Spacecraft\/SPACE\/GEO_2Body\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start7=Enabled\/SPACE\/Spacecraft\/SPACE\/GEO_AllPlanets\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start8=Enabled\/SPACE\/Spacecraft\/SPACE\/GEO_NSG\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start9=Enabled\/SPACE\/Spacecraft\/SPACE\/GEO_Drag\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start10=Enabled\/SPACE\/Spacecraft\/SPACE\/GEO_SRP\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start11=Enabled\/SPACE\/Spacecraft\/SPACE\/GPS_2Body\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start12=Enabled\/SPACE\/Spacecraft\/SPACE\/GPS_AllPlanets\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start13=Enabled\/SPACE\/Spacecraft\/SPACE\/GPS_Drag\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start14=Enabled\/SPACE\/Spacecraft\/SPACE\/GPS_NSG\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start15=Enabled\/SPACE\/Spacecraft\/SPACE\/GPS_SRP\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start16=Enabled\/SPACE\/Spacecraft\/SPACE\/Molniya_2Body\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start17=Enabled\/SPACE\/Spacecraft\/SPACE\/Molniya_AllPlanets\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start18=Enabled\/SPACE\/Spacecraft\/SPACE\/Molniya_NSG\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start19=Enabled\/SPACE\/Spacecraft\/SPACE\/Molniya_Drag\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start20=Enabled\/SPACE\/Spacecraft\/SPACE\/Molniya_SRP\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start21=Enabled\/SPACE\/Spacecraft\/SPACE\/SunSync_2Body\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start22=Enabled\/SPACE\/Spacecraft\/SPACE\/SunSync_AllPlanets\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start23=Enabled\/SPACE\/Spacecraft\/SPACE\/SunSync_NSG\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start24=Enabled\/SPACE\/Spacecraft\/SPACE\/SunSync_Drag\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start25=Enabled\/SPACE\/Spacecraft\/SPACE\/SunSync_SRP\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
[FreeformScript2]
FreeFormLine1=\/SPACE\/FF_SolarSystem.COUpdateInterval = 0;\/END\/
FreeFormLine2=\/SPACE\/FF_SolarSystem.NPUpdateInterval = 60;\/END\/
FreeFormLine3=\/SPACE\/FF_SolarSystem.ComputePolarMotion = 1;\/END\/
[FreeformScript4]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report ISS_2Body.ElapsedMinutes<15,9>, ISS_2Body.X<15,9>, ISS_2Body.Y<15,9>, ISS_2Body.Z<15,9>, ISS_2Body.VX<15,9>, ISS_2Body.VY<15,9>, ISS_2Body.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step ISS_2Body;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript5]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step ISS_2Body;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript6]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report ISS_AllPlanets.ElapsedMinutes<15,9>, ISS_AllPlanets.X<15,9>, ISS_AllPlanets.Y<15,9>, ISS_AllPlanets.Z<15,9>, ISS_AllPlanets.VX<15,9>, ISS_AllPlanets.VY<15,9>, ISS_AllPlanets.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step ISS_AllPlanets;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript53]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step ISS_AllPlanets;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript8]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report ISS_NSG.ElapsedMinutes<15,9>, ISS_NSG.X<15,9>, ISS_NSG.Y<15,9>, ISS_NSG.Z<15,9>, ISS_NSG.VX<15,9>, ISS_NSG.VY<15,9>, ISS_NSG.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step ISS_NSG;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript51]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step ISS_NSG;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript10]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report ISS_Drag.ElapsedMinutes<15,9>, ISS_Drag.X<15,9>, ISS_Drag.Y<15,9>, ISS_Drag.Z<15,9>, ISS_Drag.VX<15,9>, ISS_Drag.VY<15,9>, ISS_Drag.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step ISS_Drag;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript49]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step ISS_Drag;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript12]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report ISS_SRP.ElapsedMinutes<15,9>, ISS_SRP.X<15,9>, ISS_SRP.Y<15,9>, ISS_SRP.Z<15,9>, ISS_SRP.VX<15,9>, ISS_SRP.VY<15,9>, ISS_SRP.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step ISS_SRP;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript47]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (ISS_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step ISS_SRP;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript14]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GEO_2Body.ElapsedMinutes<15,9>, GEO_2Body.X<15,9>, GEO_2Body.Y<15,9>, GEO_2Body.Z<15,9>, GEO_2Body.VX<15,9>, GEO_2Body.VY<15,9>, GEO_2Body.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GEO_2Body;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript45]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GEO_2Body;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript16]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GEO_AllPlanets.ElapsedMinutes<15,9>, GEO_AllPlanets.X<15,9>, GEO_AllPlanets.Y<15,9>, GEO_AllPlanets.Z<15,9>, GEO_AllPlanets.VX<15,9>, GEO_AllPlanets.VY<15,9>, GEO_AllPlanets.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GEO_AllPlanets;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript43]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GEO_AllPlanets;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript18]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GEO_NSG.ElapsedMinutes<15,9>, GEO_NSG.X<15,9>, GEO_NSG.Y<15,9>, GEO_NSG.Z<15,9>, GEO_NSG.VX<15,9>, GEO_NSG.VY<15,9>, GEO_NSG.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GEO_NSG;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript41]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GEO_NSG;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript20]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GEO_Drag.ElapsedMinutes<15,9>, GEO_Drag.X<15,9>, GEO_Drag.Y<15,9>, GEO_Drag.Z<15,9>, GEO_Drag.VX<15,9>, GEO_Drag.VY<15,9>, GEO_Drag.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GEO_Drag;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript35]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GEO_Drag;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript22]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GEO_SRP.ElapsedMinutes<15,9>, GEO_SRP.X<15,9>, GEO_SRP.Y<15,9>, GEO_SRP.Z<15,9>, GEO_SRP.VX<15,9>, GEO_SRP.VY<15,9>, GEO_SRP.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GEO_SRP;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript27]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GEO_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GEO_SRP;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript24]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GPS_2Body.ElapsedMinutes<15,9>, GPS_2Body.X<15,9>, GPS_2Body.Y<15,9>, GPS_2Body.Z<15,9>, GPS_2Body.VX<15,9>, GPS_2Body.VY<15,9>, GPS_2Body.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GPS_2Body;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript21]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GPS_2Body;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript26]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GPS_AllPlanets.ElapsedMinutes<15,9>, GPS_AllPlanets.X<15,9>, GPS_AllPlanets.Y<15,9>, GPS_AllPlanets.Z<15,9>, GPS_AllPlanets.VX<15,9>, GPS_AllPlanets.VY<15,9>, GPS_AllPlanets.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GPS_AllPlanets;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript25]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GPS_AllPlanets;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript28]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GPS_NSG.ElapsedMinutes<15,9>, GPS_NSG.X<15,9>, GPS_NSG.Y<15,9>, GPS_NSG.Z<15,9>, GPS_NSG.VX<15,9>, GPS_NSG.VY<15,9>, GPS_NSG.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GPS_NSG;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript23]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GPS_NSG;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript30]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GPS_Drag.ElapsedMinutes<15,9>, GPS_Drag.X<15,9>, GPS_Drag.Y<15,9>, GPS_Drag.Z<15,9>, GPS_Drag.VX<15,9>, GPS_Drag.VY<15,9>, GPS_Drag.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GPS_Drag;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript19]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GPS_Drag;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript32]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report GPS_SRP.ElapsedMinutes<15,9>, GPS_SRP.X<15,9>, GPS_SRP.Y<15,9>, GPS_SRP.Z<15,9>, GPS_SRP.VX<15,9>, GPS_SRP.VY<15,9>, GPS_SRP.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step GPS_SRP;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript29]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (GPS_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step GPS_SRP;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript34]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report Molniya_2Body.ElapsedMinutes<15,9>, Molniya_2Body.X<15,9>, Molniya_2Body.Y<15,9>, Molniya_2Body.Z<15,9>, Molniya_2Body.VX<15,9>, Molniya_2Body.VY<15,9>, Molniya_2Body.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step Molniya_2Body;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript17]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step Molniya_2Body;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript36]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report Molniya_AllPlanets.ElapsedMinutes<15,9>, Molniya_AllPlanets.X<15,9>, Molniya_AllPlanets.Y<15,9>, Molniya_AllPlanets.Z<15,9>, Molniya_AllPlanets.VX<15,9>, Molniya_AllPlanets.VY<15,9>, Molniya_AllPlanets.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step Molniya_AllPlanets;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript15]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step Molniya_AllPlanets;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript38]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report Molniya_NSG.ElapsedMinutes<15,9>, Molniya_NSG.X<15,9>, Molniya_NSG.Y<15,9>, Molniya_NSG.Z<15,9>, Molniya_NSG.VX<15,9>, Molniya_NSG.VY<15,9>, Molniya_NSG.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step Molniya_NSG;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript31]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step Molniya_NSG;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript40]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report Molniya_Drag.ElapsedMinutes<15,9>, Molniya_Drag.X<15,9>, Molniya_Drag.Y<15,9>, Molniya_Drag.Z<15,9>, Molniya_Drag.VX<15,9>, Molniya_Drag.VY<15,9>, Molniya_Drag.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step Molniya_Drag;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript13]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step Molniya_Drag;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript42]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report Molniya_SRP.ElapsedMinutes<15,9>, Molniya_SRP.X<15,9>, Molniya_SRP.Y<15,9>, Molniya_SRP.Z<15,9>, Molniya_SRP.VX<15,9>, Molniya_SRP.VY<15,9>, Molniya_SRP.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step Molniya_SRP;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript9]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (Molniya_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step Molniya_SRP;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript44]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report SunSync_2Body.ElapsedMinutes<15,9>, SunSync_2Body.X<15,9>, SunSync_2Body.Y<15,9>, SunSync_2Body.Z<15,9>, SunSync_2Body.VX<15,9>, SunSync_2Body.VY<15,9>, SunSync_2Body.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step SunSync_2Body;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript11]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_2Body.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step SunSync_2Body;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript46]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report SunSync_AllPlanets.ElapsedMinutes<15,9>, SunSync_AllPlanets.X<15,9>, SunSync_AllPlanets.Y<15,9>, SunSync_AllPlanets.Z<15,9>, SunSync_AllPlanets.VX<15,9>, SunSync_AllPlanets.VY<15,9>, SunSync_AllPlanets.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step SunSync_AllPlanets;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript33]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_AllPlanets.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step SunSync_AllPlanets;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript48]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report SunSync_NSG.ElapsedMinutes<15,9>, SunSync_NSG.X<15,9>, SunSync_NSG.Y<15,9>, SunSync_NSG.Z<15,9>, SunSync_NSG.VX<15,9>, SunSync_NSG.VY<15,9>, SunSync_NSG.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step SunSync_NSG;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript7]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_NSG.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step SunSync_NSG;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript50]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report SunSync_Drag.ElapsedMinutes<15,9>, SunSync_Drag.X<15,9>, SunSync_Drag.Y<15,9>, SunSync_Drag.Z<15,9>, SunSync_Drag.VX<15,9>, SunSync_Drag.VY<15,9>, SunSync_Drag.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step SunSync_Drag;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript37]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_Drag.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step SunSync_Drag;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript52]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Report SunSync_SRP.ElapsedMinutes<15,9>, SunSync_SRP.X<15,9>, SunSync_SRP.Y<15,9>, SunSync_SRP.Z<15,9>, SunSync_SRP.VX<15,9>, SunSync_SRP.VY<15,9>, SunSync_SRP.VZ<15,9> to "Performance_output.report";\/END\/
FreeFormLine4=\/SPACE\/  Step SunSync_SRP;\/END\/
FreeFormLine5=\/SPACE\/End;\/END\/
FreeFormLine6=\/SPACE\/// End Mission Sequence;\/END\/
[FreeformScript39]
FreeFormLine1=\/SPACE\/// Begin Mission Sequence;\/END\/
FreeFormLine2=\/SPACE\/While (SunSync_SRP.ElapsedDays <= 30);\/END\/
FreeFormLine3=\/SPACE\/  Step SunSync_SRP;\/END\/
FreeFormLine4=\/SPACE\/End;\/END\/
FreeFormLine5=\/SPACE\/// End Mission Sequence;\/END\/
[COMMAND_SECTION]
Number_Commands=51
