% Created from the following script: AssignmentTests.m
%
% Functions used: Func_AssignmentTests.gmf, Func_AssignmentTests_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
% Begin/EndScript used to force GMAT to go into command mode. Might
% not be necessary but I've included it just in case.
 
BeginScript;
EndScript;
 
% Call function
Func_AssignmentTests
Func_AssignmentTests_nested
