% Created from the following script: StopTarget.m
%
% Functions used: Func_StopTarget.gmf, Func_StopTarget_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
GMAT reportLoc1 = './output/SystemTest/Func_StopTargetManeuver.report';
 
Create String reportLoc1_nested;
GMAT reportLoc1_nested = './output/SystemTest/Func_StopTargetManeuver_nested.report';
 
Create String reportLoc2;
GMAT reportLoc2 = './output/SystemTest/Func_StopTarget.report';
 
Create String reportLoc2_nested;
GMAT reportLoc2_nested = './output/SystemTest/Func_StopTarget_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
% Begin/EndScript used to force GMAT to go into command mode. Might
% not be necessary but I've included it just in case.
 
BeginScript;
EndScript;
 
% Call function
Func_StopTarget(reportLoc1,reportLoc2)
Func_StopTarget_nested(reportLoc1_nested,reportLoc2_nested)
