% Created from the following script: WhileIf51_15.m
%
% Functions used: Func_WhileIf51_15.gmf, Func_WhileIf51_15_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
GMAT reportLoc1 = './output/SystemTest/Func_WhileIf51_15.report';
 
Create String reportLoc1_nested;
GMAT reportLoc1_nested = './output/SystemTest/Func_WhileIf51_15_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
% Begin/EndScript used to force GMAT to go into command mode. Might
% not be necessary but I've included it just in case.
 
BeginScript;
EndScript;
 
% Call function
Func_WhileIf51_15(reportLoc1)
Func_WhileIf51_15_nested(reportLoc1_nested)
