% $Id: Func_ESL_JGM2_MSISE90_SRP.script,v 1.2 2008/05/02 19:05:36 edove Exp $

% Func_ESL_JGM2_MSISE90_SRP - This script tests to make sure 
%
% Function used: Func_ESL_JGM2_MSISE90_SRP.gmf, Func_ESL_JGM2_MSISE90_SRP_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/ 

%----------------------------------------
%---------- Spacecrafts
%----------------------------------------

Create Spacecraft DefaultSC;

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;

%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------

Create String reportLoc;
GMAT reportLoc = './output/SystemTest/Func_ESL_JGM2_MSISE90_SRP.report';

Create String reportLoc_nested;
GMAT reportLoc_nested = './output/SystemTest/Func_ESL_JGM2_MSISE90_SRP_nested.report';

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

% Begin/EndScript used to force GMAT to go into command mode. Might
% Not be necessary but I've included it just in case.
 
BeginScript;
EndScript;

% Call function
Func_ESL_JGM2_MSISE90_SRP(reportLoc);
Func_ESL_JGM2_MSISE90_SRP_nested(reportLoc_nested);