% $Id: Func_CSParams_GMAT_BPlaneTests.script,v 1.2 2008/05/02 19:05:35 edove Exp $

% Func_CSParams_GMAT_BPlaneTests - This script tests to make sure 
%
% Function used: Func_CSParams_GMAT_BPlaneTests.gmf, Func_CSParams_GMAT_BPlaneTests_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/ 

%----------------------------------------
%---------- Spacecrafts
%----------------------------------------

Create Spacecraft DefaultSC;

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;

%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------

Create String reportLoc1;
GMAT reportLoc1 = './output/SystemTest/Func_EarthBPlaneData.report';

Create String reportLoc2;
GMAT reportLoc2 = './output/SystemTest/Func_MoonBPlaneData.report';

Create String reportLoc_nested1;
GMAT reportLoc_nested1 = './output/SystemTest/Func_EarthBPlaneData_nested.report';

Create String reportLoc_nested2;
GMAT reportLoc_nested2 = './output/SystemTest/Func_MoonBPlaneData_nested.report';

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

% Begin/EndScript used to force GMAT to go into command mode. Might
% Not be necessary but I've included it just in case.
 
BeginScript;
EndScript;

% Call functions
Func_CSParams_GMAT_BPlaneTests(reportLoc1,reportLoc2);
Func_CSParams_GMAT_BPlaneTests_nested(reportLoc_nested1,reportLoc_nested2);