% Created from the following script: ForArray.m
%
% Functions used: Func_ForArray.gmf, Func_ForArray_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
GMAT reportLoc1 = './output/SystemTest/Func_ForArray.report';
 
Create String reportLoc1_nested;
GMAT reportLoc1_nested = './output/SystemTest/Func_ForArray_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
% Begin/EndScript used to force GMAT to go into command mode. Might
% not be necessary but I've included it just in case.
 
BeginScript;
EndScript;
 
% Call function
Func_ForArray(reportLoc1)
Func_ForArray_nested(reportLoc1_nested)
