% Created from the following script: ToggleTest.m
%
% Functions used: Func_ToggleTest.gmf, Func_ToggleTest_nested.gmf
% Function path: ./output/SystemTest/
% Outputs to: ./output/SystemTest/
 
%----------------------------------------
%---------- Spacecrafts
%----------------------------------------
 
Create Spacecraft DefaultSC;
 
%----------------------------------------
%---------- Propagators
%----------------------------------------
 
Create ForceModel DefaultProp_ForceModel;
 
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
 
%----------------------------------------
%---------- Variables, Arrays, Strings
%----------------------------------------
 
Create String reportLoc1;
GMAT reportLoc1 = './output/SystemTest/Func_ToggleTestFile1.report';
 
Create String reportLoc1_nested;
GMAT reportLoc1_nested = './output/SystemTest/Func_ToggleTestFile1_nested.report';
 
Create String reportLoc2;
GMAT reportLoc2 = './output/SystemTest/Func_ToggleTestFile2.report';
 
Create String reportLoc2_nested;
GMAT reportLoc2_nested = './output/SystemTest/Func_ToggleTestFile2_nested.report';
 
 
%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
 
% Begin/EndScript used to force GMAT to go into command mode. Might
% not be necessary but I've included it just in case.
 
BeginScript;
EndScript;
 
% Call function
Func_ToggleTest(reportLoc1,reportLoc2)
Func_ToggleTest_nested(reportLoc1_nested,reportLoc2_nested)
