% ------------------------------------------------
% Test validation scripts for Spacecraft-Ballistic
% ------------------------------------------------
Create Spacecraft DefaultSC;

Create Variable testVar;
GMAT testVar.Expression = -3;
Create String testString;
GMAT testString.Expression = TEST;
Create Array testArray[2, 2];
GMAT testArray.Expression = testArray;
GMAT testArray(1, 1) = -4;

% --------
% Dry Mass
% --------
GMAT DefaultSC.DryMass = DoesNotExist;
GMAT DefaultSC.DryMass = -1.0;
GMAT DefaultSC.DryMass = 0.0;
GMAT DefaultSC.DryMass = 1.0;
GMAT DefaultSC.DryMass = 1;
GMAT DefaultSC.DryMass = testVar;
GMAT DefaultSC.DryMass = testString;
GMAT DefaultSC.DryMass = testArray(1,1);

% --
% Cd
% --
GMAT DefaultSC.Cd = DoesNotExist;
GMAT DefaultSC.Cd = -1.0;
GMAT DefaultSC.Cd = 0.0;
GMAT DefaultSC.Cd = 1.0;
GMAT DefaultSC.Cd = 1;
GMAT DefaultSC.Cd = testVar;
GMAT DefaultSC.Cd = testString;
GMAT DefaultSC.Cd = testArray(1,1);

% --
% Cr
% --
GMAT DefaultSC.Cr = DoesNotExist;
GMAT DefaultSC.Cr = -1.0;
GMAT DefaultSC.Cr = 0.0;
GMAT DefaultSC.Cr = 1.0;
GMAT DefaultSC.Cr = 1;
GMAT DefaultSC.Cr = testVar;
GMAT DefaultSC.Cr = testString;
GMAT DefaultSC.Cr = testArray(1,1);

% ---------
% Drag Area
% ---------
GMAT DefaultSC.DragArea = DoesNotExist;
GMAT DefaultSC.DragArea = -1.0;	
GMAT DefaultSC.DragArea = 0.0;
GMAT DefaultSC.DragArea = 1.0;
GMAT DefaultSC.DragArea = 1;
GMAT DefaultSC.DragArea = testVar;
GMAT DefaultSC.DragArea = testString;
GMAT DefaultSC.DragArea = testArray(1,1);

% --------
% SRP Area
% --------
GMAT DefaultSC.SRPArea = DoesNotExist;
GMAT DefaultSC.SRPArea = -1.0;
GMAT DefaultSC.SRPArea = 0.0;
GMAT DefaultSC.SRPArea = 1.0;
GMAT DefaultSC.SRPArea = 1;
GMAT DefaultSC.SRPArea = testVar;
GMAT DefaultSC.SRPArea = testString;
GMAT DefaultSC.SRPArea = testArray(1,1);
