Create MatlabFunction matlabFunction;
Create Spacecraft sc1, sc2, sc3;
Create Variable x, y, z, m, n;
Create Array array1[1, 3] array2[2, 3] array3[3, 1];
Create String str1, str2, str3;

GMAT [nonExistantOutput] = NonExistantFunction (NonExistantInput);
GMAT [x] = NonExistantFunction (NonExistantInput);
GMAT [nonExistantOutput] = NonExistantFunction (x);
GMAT [x] = NonExistantFunction (y);

GMAT [x] = matlabFunction (y);
[x] = matlabFunction (y);
GMAT = matlabFunction (y);
GMAT matlabFunction (y);
matlabFunction (y);
GMAT [x] = (y);
GMAT [x] = matlabFunction ();
GMAT [x] = matlabFunction ;
GMAT matlabFunction;
GMAT DoesNotExist;

GMAT [x, y, z] = matlabFunction (m, n);
GMAT [ x, y, z ] = matlabFunction (m, n);
GMAT [x, y, z] = matlabFunction ( m, n );
GMAT [ x, y, z ] = matlabFunction ( m, n );
GMAT [x y z] = matlabFunction (m, n);
GMAT [x, y, z] = matlabFunction (m n);
GMAT [x y z] = matlabFunction (m n);
[x, y, z] = matlabFunction (m, n);
GMAT [x, y, z] = matlabFunction (m, n)
[x, y, z] = matlabFunction (m, n)

GMAT [str1] = matlabFunction (str2);
GMAT [str1, str2] = matlabFunction (str2);
GMAT [str1] = matlabFunction (str2, str3);
GMAT matlabFunction (str2);
GMAT [str1] = matlabFunction ();
GMAT [str1] = matlabFunction;

GMAT [sc1] = matlabFunction (sc2);
GMAT [sc1, sc2] = matlabFunction (sc2);
GMAT [sc1] = matlabFunction (sc2, sc3);
GMAT matlabFunction (sc2);
GMAT [sc1] = matlabFunction ();
GMAT [sc1] = matlabFunction;

GMAT [array1] = matlabFunction (array2);
GMAT [array1, array2] = matlabFunction (array3);
GMAT [array1] = matlabFunction (array2, array3);
GMAT matlabFunction (array1);
GMAT matlabFunction (array1, array2);
GMAT [array1] = matlabFunction ();
GMAT [array1] = matlabFunction;

GMAT [array1(0,0)] = matlabFunction (array2);
GMAT [array1 (0,0)] = matlabFunction (array2(0,0));
GMAT [array1 (0,5)] = matlabFunction (array2(0,0));
GMAT [array1 (0,0)] = matlabFunction (array2(0,5));
GMAT [ array1 ] = matlabFunction (array2(0,0));
GMAT [ array1(0,0), array1(0, 1) ] = matlabFunction (array2(0,0), array2(0,1));

GMAT [1] = matlabFunction();
GMAT [1.0] = matlabFunction();
GMAT [sc1] = matlabFunction();
GMAT [DoesNotExist] = matlabFunction();

GMAT y = matlabFunction(1);
GMAT y = matlabFunction(1.0);
GMAT y = matlabFunction(sc1);
GMAT y = matlabFunction(sc1.EarthMJ2000Eq.X);
GMAT y = matlabFunction(DoesNotExist);

GMAT matlabFunction(1);
GMAT matlabFunction(1.0);
GMAT matlabFunction(sc1);
GMAT matlabFunction(sc1.EarthMJ2000Eq.X);
GMAT matlabFunction(DoesNotExist);


GMAT y = 1(x);
GMAT y = 1.0(x);
GMAT y = x(sc1);
GMAT y = sc1.EarthMJ2000Eq.X(x);
GMAT y = DoesNotExist(x);
