
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

%---------------------------------------
%  Test for use of nonexistent resources
%---------------------------------------
%  
Toggle DNE On;
Toggle XYPlot1 DNE1.XYPlot1 Off
Toggle XYPlot1 DNE Off;
Toggle DNE XYPlot1 On;

%---------------------------------------
%  Test for improper use of parameters
%---------------------------------------

%---- Non-existent parameters
Toggle Sat.DNE Off;
Toggle XYPlot1 On Off;

%---- Improper use of allowed parameters

%---- Disallowed parameters
Toggle WrongArray(2,1) Off;

%---- Disallowed use of numbers
Toggle 1.0 On;  % comment here 
Toggle 1.0 1.0 On;
1.0 Toggle Sat.X Off;

%---------------------------------------
%  Test for improper use of resources
%---------------------------------------
Toggle WrongSat Off;
Toggle WrongProp Sat.X On;

%---------------------------------------
%  Test for missing elements
%---------------------------------------
Toggle OpenGL;
Toggle Off;

%-------------------------------------------------
%  Test for improper use of conditional operators
%-------------------------------------------------
Toggle OpenGL < 3 On;

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%---  Missing Parentheses ----
%  not applicable

%---  Missing curly brackets
%  not applicable

%--- Mixed incorrect brackets
(Toggle) OpenGL Off      % another comment
Toggle OpenGL (Sat.X) Off
Toggle (OpenGL) Off
Toggle (OpenGL Sat.X) Off
Toggle {OpenGL} Off
Toggle OpenGL {Sat.X} Off;
Toggle {OpenGL Sat.X} Off;

%----------------------------------------------------------
%  Test for improper use of closing branch command statement
%----------------------------------------------------------
%  not applicable

%--------------------------------
%-------  Comma Errors    -------
%--------------------------------

%---  Missing commas
%  not applicable

%---  Improper use of commas
%  Are these not allowed?
Toggle , OpenGL XYPlot1 Off;
Toggle OpenGL XYPlot1, On  % not catching