
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 XYPlot2 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

PenDown XYPlot1 XYPlot2

%---------------------------------------
%  Test for use of nonexistent resources
%---------------------------------------
%  The script line is not output for these errors
PenDown DNE
PenDown Sat.X DNE1.Y DNE2.Y
PenDown Sat.X DNE;
PenDown DNE Sat.X;

%---------------------------------------
%  Test for improper use of parameters
%---------------------------------------

%---- Non-existent parameters
PenDown Sat.DNE

%---- Improper use of allowed parameters

%---- Disallowed parameters
PenDown WrongArray(2,1);

%---- Disallowed use of numbers
PenDown 1.0;
PenDown 1.0 1.0;
1.0 PenDown Sat.X;

%---------------------------------------
%  Test for improper use of resources
%---------------------------------------
PenDown WrongSat;
PenDown WrongProp Sat.X;

%---------------------------------------
%  Test for missing elements
%---------------------------------------
PenDown

%-------------------------------------------------
%  Test for improper use of conditional operators
%-------------------------------------------------
PenDown OpenGL < 3;

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%---  Missing Parenthesis ----
%  not applicable

%---  Missing curly brackets
%  not applicable

%--- Mixed incorrect brackets
(PenDown) OpenGL
PenDown OpenGL (Sat.X)
PenDown (OpenGL)
PenDown (OpenGL Sat.X)
PenDown {OpenGL}
PenDown OpenGL {Sat.X}
PenDown {OpenGL Sat.X}

%----------------------------------------------------------
%  Test for improper use of closing branch command statement
%----------------------------------------------------------
%  not applicable

%--------------------------------
%-------  Comma Errors    -------
%--------------------------------

%---  Missing commas
%  not applicable

%---  Improper use of commas
%  Are these not allowed?
PenDown , OpenGL Sat.X Sat.Y
PenDown OpenGL Sat.X, Sat.Y