
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

%--------------------------------------
%  Command specific modifications
%--------------------------------------
Sat.Tanks ={Tank};
Sat.Thrusters = {Thruster}
Create Spacecraft Sat2;

%---------------------------------------
%  This should be OK
%---------------------------------------
BeginFiniteBurn FiniteBurn(Sat, Sat2)

%***************************************************************
%--------------------------------------------------------------
%-----------  Command Exceptions !!!
%--------------------------------------------------------------
%***************************************************************

%***************************************************************
%--------------------------------------------------------------
%-----------  Interpreter Exceptions !!!
%--------------------------------------------------------------
%***************************************************************

%---------------------------------------
%  Use of nonexistent resources
%---------------------------------------
BeginFiniteBurn DNE(Sat);
BeginFiniteBurn FiniteBurn(DNE);
BeginFiniteBurn FiniteBurn(Sat, DNE);
BeginFiniteBurn FiniteBurn(DNE, Sat);

%---------------------------------------
%  Improper use of resources
%---------------------------------------
BeginFiniteBurn FiniteBurn(Prop);
BeginFiniteBurn Prop(Sat);
BeginFiniteBurn Prop(FiniteBurn);
BeginFiniteBurn CoordSys(Sat);

%---------------------------------------
%  Improper use of parameters
%---------------------------------------

%---- Improper use of allowed parameters
%  not applicable

%---- Disallowed parameters
BeginFiniteBurn WrongSat.X(Sat)
BeginFiniteBurn FiniteBurn(WrongSat.X)
BeginFiniteBurn WrongVar(Sat)
BeginFiniteBurn FiniteBurn(WrongVar)
BeginFiniteBurn WrongArray(Sat)
BeginFiniteBurn FiniteBurn(WrongArray)

%---------------------------------------
%  Improper use of real numbers
%---------------------------------------
1.0 FiniteBurn(Sat);
BeginFiniteBurn 1.0(Sat);
BeginFiniteBurn FiniteBurn(1.0)
BeginFiniteBurn FiniteBurn(Sat 1.0)

%-------------------------------------------------
%  Improper use of conditional operators
%-------------------------------------------------
BeginFiniteBurn FiniteBurn(Sat < 1.0)
BeginFiniteBurn FiniteBurn(2.0 == Sat.X)

%---------------------------------------------------
%  Improper use of brackets and parentheses
%---------------------------------------------------

%---  Missing Parenthesis(es) ----
BeginFiniteBurn FiniteBurn Sat
BeginFiniteBurn FiniteBurn Sat)
%  Utility Exception  
BeginFiniteBurn FiniteBurn (Sat
BeginFiniteBurn FiniteBurn Sat, WrongSat)
%  Utility Exception  
BeginFiniteBurn FiniteBurn (Sat, WrongSat
BeginFiniteBurn FiniteBurn Sat, WrongSat

%---  Missing curly brackets
%  not applicable

%--- Miscellaneous bracket and parentheses errors
BeginFiniteBurn FiniteBurn{Sat}
BeginFiniteBurn FiniteBurn[Sat]
BeginFiniteBurn FiniteBurn(Sat}
% 
BeginFiniteBurn FiniteBurn{Sat)
% 
BeginFiniteBurn FiniteBurn[Sat)
BeginFiniteBurn FiniteBurn(Sat]
BeginFiniteBurn(Sat);
BeginFiniteBurn (FiniteBurn) Sat
BeginFiniteBurn {FiniteBurn} Sat
BeginFiniteBurn [FiniteBurn] Sat

%---------------------------------------
%  Missing command elements
%---------------------------------------
BeginFiniteBurn FiniteBurn();
BeginFiniteBurn  (Sat);
FiniteBurn(Sat);

%--------------------------------
%  Comma errors    
%--------------------------------

%---  Missing commas
%  
BeginFiniteBurn FiniteBurn(Sat Sat2)

%---  Improper use of commas
,BeginFiniteBurn FiniteBurn(Sat);
BeginFiniteBurn, FiniteBurn(Sat);
BeginFiniteBurn FiniteBurn,(Sat);
BeginFiniteBurn FiniteBurn(,Sat);
BeginFiniteBurn FiniteBurn(Sat,);

%-------------------------------
%  Closing branch command error
%-------------------------------
%  
% N/A - BeginFiniteBurn/EndFiniteBurn are not branch commands