
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 XYPlot2 XYPlot3 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

ClearPlot XYPlot1 XYPlot2

%---------------------------------------
%  Test for use of nonexistent resources
%---------------------------------------
%  The script line is not output for these errors
ClearPlot DNE
ClearPlot Sat.X DNE1.Y DNE2.Y
ClearPlot Sat.X DNE;
ClearPlot DNE Sat.X;

%---------------------------------------
%  Test for improper use of parameters
%---------------------------------------

%---- Non-existent parameters
ClearPlot Sat.DNE

%---- Improper use of allowed parameters

%---- Disallowed parameters
ClearPlot WrongArray(2,1);

%---- Disallowed use of numbers
ClearPlot 1.0;
ClearPlot 1.0 1.0;
1.0 ClearPlot Sat.X;

%---------------------------------------
%  Test for improper use of resources
%---------------------------------------
ClearPlot WrongSat;
ClearPlot WrongProp Sat.X;

%---------------------------------------
%  Test for missing elements
%---------------------------------------
ClearPlot

%-------------------------------------------------
%  Test for improper use of conditional operators
%-------------------------------------------------
ClearPlot OpenGL < 3;

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%---  Missing Parenthesis ----
%  not applicable

%---  Missing curly brackets
%  not applicable

%--- Mixed incorrect brackets
(ClearPlot) OpenGL
ClearPlot OpenGL (Sat.X)
ClearPlot (OpenGL)
ClearPlot (OpenGL Sat.X)
ClearPlot {OpenGL}
ClearPlot OpenGL {Sat.X}
ClearPlot {OpenGL Sat.X}
ClearPlot XYPlot1(XYPlot2,XYPlot3)

%----------------------------------------------------------
%  Test for improper use of closing branch command statement
%----------------------------------------------------------
%  not applicable

%--------------------------------
%-------  Comma Errors    -------
%--------------------------------

%---  Missing commas
%  not applicable

%---  Improper use of commas
%  Are these not allowed?
ClearPlot , OpenGL Sat.X Sat.Y
ClearPlot OpenGL Sat.X, Sat.Y