
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

%--------------------------------------
%  Command specific modifications
%--------------------------------------
Sat.Tanks ={Tank};
Sat.Thrusters = {Thruster}
Create Spacecraft Sat2;

%---------------------------------------
%  This should be OK
%---------------------------------------
BeginFiniteBurn FiniteBurn(Sat, Sat2)
EndFiniteBurn FiniteBurn(Sat, Sat2)

%***************************************************************
%--------------------------------------------------------------
%-----------  Command Exceptions !!!
%--------------------------------------------------------------
%***************************************************************

%***************************************************************
%--------------------------------------------------------------
%-----------  Interpreter Exceptions !!!
%--------------------------------------------------------------
%***************************************************************

%---------------------------------------
%  Use of nonexistent resources
%---------------------------------------
EndFiniteBurn DNE(Sat);
EndFiniteBurn FiniteBurn(DNE);
EndFiniteBurn FiniteBurn(Sat, DNE);
EndFiniteBurn FiniteBurn(DNE, Sat);

%---------------------------------------
%  Improper use of resources
%---------------------------------------
EndFiniteBurn FiniteBurn(Prop);
EndFiniteBurn Prop(Sat);
EndFiniteBurn Prop(FiniteBurn);
EndFiniteBurn CoordSys(Sat);

%---------------------------------------
%  Improper use of parameters
%---------------------------------------

%---- Improper use of allowed parameters
%  not applicable

%---- Disallowed parameters
EndFiniteBurn WrongSat.X(Sat)
EndFiniteBurn FiniteBurn(WrongSat.X)
EndFiniteBurn WrongVar(Sat)
EndFiniteBurn FiniteBurn(WrongVar)
EndFiniteBurn WrongArray(Sat)
EndFiniteBurn FiniteBurn(WrongArray)

%---------------------------------------
%  Improper use of real numbers
%---------------------------------------
1.0 FiniteBurn(Sat);
EndFiniteBurn 1.0(Sat);
EndFiniteBurn FiniteBurn(1.0)
EndFiniteBurn FiniteBurn(Sat 1.0)

%-------------------------------------------------
%  Improper use of conditional operators
%-------------------------------------------------
EndFiniteBurn FiniteBurn(Sat < 1.0)
EndFiniteBurn FiniteBurn(2.0 == Sat.X)

%---------------------------------------------------
%  Improper use of brackets and parentheses
%---------------------------------------------------

%---  Missing Parenthesis(es) ----
EndFiniteBurn FiniteBurn Sat
EndFiniteBurn FiniteBurn Sat)
%  Utility Exception  
EndFiniteBurn FiniteBurn (Sat
EndFiniteBurn FiniteBurn Sat, WrongSat)
%  Utility Exception  
EndFiniteBurn FiniteBurn (Sat, WrongSat
EndFiniteBurn FiniteBurn Sat, WrongSat

%---  Missing curly brackets
%  not applicable

%--- Miscellaneous bracket and parentheses errors
EndFiniteBurn FiniteBurn{Sat}
EndFiniteBurn FiniteBurn[Sat]
EndFiniteBurn FiniteBurn(Sat}
% 
EndFiniteBurn FiniteBurn{Sat)
% 
EndFiniteBurn FiniteBurn[Sat)
EndFiniteBurn FiniteBurn(Sat]
EndFiniteBurn(Sat);
EndFiniteBurn (FiniteBurn) Sat
EndFiniteBurn {FiniteBurn} Sat
EndFiniteBurn [FiniteBurn] Sat

%---------------------------------------
%  Missing command elements
%---------------------------------------
EndFiniteBurn FiniteBurn();
EndFiniteBurn  (Sat);
FiniteBurn(Sat);

%--------------------------------
%  Comma errors    
%--------------------------------

%---  Missing commas
%  
EndFiniteBurn FiniteBurn(Sat Sat2)

%---  Improper use of commas
,EndFiniteBurn FiniteBurn(Sat);
EndFiniteBurn, FiniteBurn(Sat);
EndFiniteBurn FiniteBurn,(Sat);
EndFiniteBurn FiniteBurn(,Sat);
EndFiniteBurn FiniteBurn(Sat,);

%-------------------------------
%  Closing branch command error
%-------------------------------
%  
% N/A - EndFiniteBurn/EndFiniteBurn are not branch commands