
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

%---------------------------------------
%  Test for use of nonexistent resources
%---------------------------------------
%  The script line is not output for these errors
Stop DNE
Stop Sat.X DNE1.Y DNE2.Y
Stop Sat.X DNE;
Stop DNE Sat.X;

%---------------------------------------
%  Test for improper use of parameters
%---------------------------------------

%---- Non-existent parameters
Stop Sat.DNE

%---- Improper use of allowed parameters

%---- Disallowed parameters
Stop WrongArray(2,1);

%---- Disallowed use of numbers
Stop 1.0;
Stop 1.0 1.0;
1.0 Stop Sat.X;

%---------------------------------------
%  Test for improper use of resources
%---------------------------------------
Stop WrongSat;
Stop WrongProp Sat.X;

%---------------------------------------
%  Test for missing elements
%---------------------------------------
% N/A

%-------------------------------------------------
%  Test for improper use of conditional operators
%-------------------------------------------------
Stop OpenGL < 3;

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%---  Missing Parenthesis ----
%  not applicable

%---  Missing curly brackets
%  not applicable

%--- Mixed incorrect brackets
(Stop) OpenGL
Stop OpenGL (Sat.X)
Stop (OpenGL)
Stop (OpenGL Sat.X)
Stop {OpenGL}
Stop OpenGL {Sat.X}
Stop {OpenGL Sat.X}

%----------------------------------------------------------
%  Test for improper use of closing branch command statement
%----------------------------------------------------------
%  not applicable

%--------------------------------
%-------  Comma Errors    -------
%--------------------------------

%---  Missing commas
%  not applicable

%---  Improper use of commas
%  Are these not allowed?
Stop , OpenGL Sat.X Sat.Y
Stop OpenGL Sat.X, Sat.Y

%----------------------------------------------------------
%  Test for erroneous text after the Stop statement
%----------------------------------------------------------
Stop other-stuff-that-should-not-be-here;
Stop % but inline comments should be OK


