[COMMAND1]
Command1=Enabled\/SPACE\/FreeForm\/SPACE\/Freeform Script\/SPACE\/FreeformScript2\/SPACE\/\/SPACE\/
[COMMAND2]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/AllPlanets.ElapsedDays <= 14\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND3]
Command1=Enabled\/SPACE\/Report\/SPACE\/AllPlanets.ElapsedMinutes<15,9>, AllPlanets.X<15,9>, AllPlanets.Y<15,9>, AllPlanets.Z<15,9>, AllPlanets.VX<15,9>, AllPlanets.VY<15,9>, AllPlanets.VZ<15,9>\/Delimit\/AllPlanets.ElapsedMinutes<15,9>\/Delimit\/AllPlanets.X<15,9>\/Delimit\/AllPlanets.Y<15,9>\/Delimit\/AllPlanets.Z<15,9>\/Delimit\/AllPlanets.VX<15,9>\/Delimit\/AllPlanets.VY<15,9>\/Delimit\/AllPlanets.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_EML2_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND4]
Command1=Enabled\/SPACE\/Report\/SPACE\/AllPlanets.ElapsedMinutes<15,9>, AllPlanets.X<15,9>, AllPlanets.Y<15,9>, AllPlanets.Z<15,9>, AllPlanets.VX<15,9>, AllPlanets.VY<15,9>, AllPlanets.VZ<15,9>\/Delimit\/AllPlanets.ElapsedMinutes<15,9>\/Delimit\/AllPlanets.X<15,9>\/Delimit\/AllPlanets.Y<15,9>\/Delimit\/AllPlanets.Z<15,9>\/Delimit\/AllPlanets.VX<15,9>\/Delimit\/AllPlanets.VY<15,9>\/Delimit\/AllPlanets.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_EML2HPOP_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[FORMAT_SECTION]
Position=199
ProjectDir=C:\GMAT_results\TruthFiles\FF\EarthMoonL2\
ProjectType=1
NumLines=43
0CWObjectList0=225
0CWObjectListLast0=199
0CWObjectList1=225
0CWObjectListLast1=199
0CWObjectList2=-1
0CWObjectListLast2=-1
0CWObjectList3=520
0CWObjectListLast3=460
1CWObjectList0=228
1CWObjectListLast0=199
1CWObjectList1=228
1CWObjectListLast1=199
1CWObjectList2=-1
1CWObjectListLast2=-1
1CWObjectList3=530
1CWObjectListLast3=460
2CWObjectList0=228
2CWObjectListLast0=199
2CWObjectList1=228
2CWObjectListLast1=199
2CWObjectList2=-1
2CWObjectListLast2=-1
2CWObjectList3=530
2CWObjectListLast3=460
3CWObjectList0=231
3CWObjectListLast0=201
3CWObjectList1=-1
3CWObjectListLast1=-1
3CWObjectList2=154
3CWObjectListLast2=134
3CWObjectList3=587
3CWObjectListLast3=509
4CWObjectList0=83
4CWObjectListLast0=72
4CWObjectList1=222
4CWObjectListLast1=193
4CWObjectList2=333
4CWObjectListLast2=289
4CWObjectList3=333
4CWObjectListLast3=289
CWMDS0=69
CWMDSLast0=61
CWMDS1=335
CWMDSLast1=295
CWMDS2=355
CWMDSLast2=312
CWMDS3=169
CWMDSLast3=148
ActivePage=0
MDSRecord=1
[COMMAND5]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 2 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND6]
Command1=Enabled\/SPACE\/Step\/SPACE\/AllPlanets\/SPACE\/\/SPACE\/
[COMMAND7]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND8]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND9]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/AllPlanets_SRP.ElapsedDays <= 14\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND10]
Command1=Enabled\/SPACE\/Report\/SPACE\/AllPlanets_SRP.ElapsedMinutes<15,9>, AllPlanets_SRP.X<15,9>, AllPlanets_SRP.Y<15,9>, AllPlanets_SRP.Z<15,9>, AllPlanets_SRP.VX<15,9>, AllPlanets_SRP.VY<15,9>, AllPlanets_SRP.VZ<15,9>\/Delimit\/AllPlanets_SRP.ElapsedMinutes<15,9>\/Delimit\/AllPlanets_SRP.X<15,9>\/Delimit\/AllPlanets_SRP.Y<15,9>\/Delimit\/AllPlanets_SRP.Z<15,9>\/Delimit\/AllPlanets_SRP.VX<15,9>\/Delimit\/AllPlanets_SRP.VY<15,9>\/Delimit\/AllPlanets_SRP.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_EML2_AllPlanets_0_0_SRP.report\/SPACE\/\/SPACE\/
[COMMAND11]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 2 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND12]
Command1=Enabled\/SPACE\/Step\/SPACE\/AllPlanets_SRP\/SPACE\/\/SPACE\/
[COMMAND13]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND14]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND15]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/ESM_JGM.ElapsedDays <= 14\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND16]
Command1=Enabled\/SPACE\/Report\/SPACE\/ESM_JGM.ElapsedMinutes<15,9>, ESM_JGM.X<15,9>, ESM_JGM.Y<15,9>, ESM_JGM.Z<15,9>, ESM_JGM.VX<15,9>, ESM_JGM.VY<15,9>, ESM_JGM.VZ<15,9>\/Delimit\/ESM_JGM.ElapsedMinutes<15,9>\/Delimit\/ESM_JGM.X<15,9>\/Delimit\/ESM_JGM.Y<15,9>\/Delimit\/ESM_JGM.Z<15,9>\/Delimit\/ESM_JGM.VX<15,9>\/Delimit\/ESM_JGM.VY<15,9>\/Delimit\/ESM_JGM.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_EML2_EarthSunLuna_JGM2_0_0.report\/SPACE\/\/SPACE\/
[COMMAND17]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 2 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND18]
Command1=Enabled\/SPACE\/Step\/SPACE\/ESM_JGM\/SPACE\/\/SPACE\/
[COMMAND19]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND20]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND21]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/ESM.ElapsedDays <= 14\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND22]
Command1=Enabled\/SPACE\/Report\/SPACE\/ESM.ElapsedMinutes<15,9>, ESM.X<15,9>, ESM.Y<15,9>, ESM.Z<15,9>, ESM.VX<15,9>, ESM.VY<15,9>, ESM.VZ<15,9>\/Delimit\/ESM.ElapsedMinutes<15,9>\/Delimit\/ESM.X<15,9>\/Delimit\/ESM.Y<15,9>\/Delimit\/ESM.Z<15,9>\/Delimit\/ESM.VX<15,9>\/Delimit\/ESM.VY<15,9>\/Delimit\/ESM.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_EML2_EarthSunLuna_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND23]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 2 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND24]
Command1=Enabled\/SPACE\/Step\/SPACE\/ESM\/SPACE\/\/SPACE\/
[COMMAND25]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND26]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[CopyOfISS]
EphemFileType=Unknown
UseEphem=0
[COMMAND27]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 60 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND28]
Command1=Enabled\/SPACE\/Step\/SPACE\/Molniya\/SPACE\/\/SPACE\/
[COMMAND29]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND30]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND31]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/ISS.ElapsedDays <= 1.007\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND32]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/CountTime = 0\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND33]
Command1=Disabled\/SPACE\/Report\/SPACE\/ISS.ElapsedDays<15,9>, ISS.X<15,9>, ISS.Y<15,9>, ISS.Z<15,9>, ISS.VX<15,9>, ISS.VY<15,9>, ISS.VZ<15,9>, CountTime<15,9>, ISS.ElapsedSeconds<15,9>\/Delimit\/ISS.ElapsedDays<15,9>\/Delimit\/ISS.X<15,9>\/Delimit\/ISS.Y<15,9>\/Delimit\/ISS.Z<15,9>\/Delimit\/ISS.VX<15,9>\/Delimit\/ISS.VY<15,9>\/Delimit\/ISS.VZ<15,9>\/Delimit\/CountTime<15,9>\/Delimit\/ISS.ElapsedSeconds<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0.Report\/SPACE\/\/SPACE\/
[COMMAND34]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND35]
Command1=Disabled\/SPACE\/Step\/SPACE\/ISS\/SPACE\/\/SPACE\/
[COMMAND36]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/Dummy = ( ISS.ElapsedSeconds )\/Delimit\/Variable\/Operator\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND37]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/CountTime > 0 and Flag = 0\/Delimit\/Variable\/Operator\/Number\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND38]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/Flag = ( 1 )\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND39]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/SS = ( Dummy )\/Delimit\/Variable\/Operator\/Variable\/Operator\/Object Parameter\/SPACE\/\/SPACE\/
[COMMAND40]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND41]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/CountTime = 0\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND42]
Command1=Disabled\/SPACE\/Report\/SPACE\/ISS.ElapsedDays<15,9>, ISS.X<15,9>, ISS.Y<15,9>, ISS.Z<15,9>, ISS.VX<15,9>, ISS.VY<15,9>, ISS.VZ<15,9>, CountTime<15,9>, ISS.ElapsedSeconds<15,9>\/Delimit\/ISS.ElapsedDays<15,9>\/Delimit\/ISS.X<15,9>\/Delimit\/ISS.Y<15,9>\/Delimit\/ISS.Z<15,9>\/Delimit\/ISS.VX<15,9>\/Delimit\/ISS.VY<15,9>\/Delimit\/ISS.VZ<15,9>\/Delimit\/CountTime<15,9>\/Delimit\/ISS.ElapsedSeconds<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0.Report\/SPACE\/\/SPACE\/
[COMMAND43]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND44]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/ReportTime = ( CountTime * SS )\/Delimit\/Variable\/Operator\/Variable\/Operator\/Variable\/SPACE\/\/SPACE\/
[COMMAND45]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/ReportTime = 600\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND46]
Command1=Disabled\/SPACE\/Report\/SPACE\/ISS.ElapsedDays<15,9>, ISS.X<15,9>, ISS.Y<15,9>, ISS.Z<15,9>, ISS.VX<15,9>, ISS.VY<15,9>, ISS.VZ<15,9>, CountTime<15,9>, ISS.ElapsedSeconds<15,9>\/Delimit\/ISS.ElapsedDays<15,9>\/Delimit\/ISS.X<15,9>\/Delimit\/ISS.Y<15,9>\/Delimit\/ISS.Z<15,9>\/Delimit\/ISS.VX<15,9>\/Delimit\/ISS.VY<15,9>\/Delimit\/ISS.VZ<15,9>\/Delimit\/CountTime<15,9>\/Delimit\/ISS.ElapsedSeconds<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0.Report\/SPACE\/\/SPACE\/
[COMMAND47]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/CountTime = ( 0 )\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND48]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND49]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/CountTime = ( CountTime + 1 )\/Delimit\/Variable\/Operator\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND50]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND51]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/CopyOfISS.ElapsedDays < 1\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND52]
Command1=Disabled\/SPACE\/View\/SPACE\/CopyOfISS\/SPACE\/\/SPACE\/
[COMMAND53]
Command1=Disabled\/SPACE\/Report\/SPACE\/CopyOfISS.ElapsedMinutes<15,9>, CopyOfISS.X<15,9>, CopyOfISS.Y<15,9>, CopyOfISS.Z<15,9>, CopyOfISS.VX<15,9>, CopyOfISS.VY<15,9>, CopyOfISS.VZ<15,9>\/Delimit\/CopyOfISS.ElapsedMinutes<15,9>\/Delimit\/CopyOfISS.X<15,9>\/Delimit\/CopyOfISS.Y<15,9>\/Delimit\/CopyOfISS.Z<15,9>\/Delimit\/CopyOfISS.VX<15,9>\/Delimit\/CopyOfISS.VY<15,9>\/Delimit\/CopyOfISS.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0_check.Report\/SPACE\/\/SPACE\/
[COMMAND54]
Command1=Disabled\/SPACE\/Step\/SPACE\/CopyOfISS to (CopyOfISS.ElapsedMinutes < 10)\/SPACE\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND55]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[GEO]
EphemFileType=Unknown
UseEphem=0
[GPS]
EphemFileType=Unknown
UseEphem=0
[SunSync]
EphemFileType=Unknown
UseEphem=0
[Molniya]
EphemFileType=Unknown
UseEphem=0
[AllPlanets_SRP]
EphemFileType=Unknown
UseEphem=0
[ESM_JGM]
EphemFileType=Unknown
UseEphem=0
[ESM]
EphemFileType=Unknown
UseEphem=0
[AllPlanets]
EphemFileType=Unknown
UseEphem=0
[START_SECTION]
Start1=Enabled\/SPACE\/Spacecraft\/SPACE\/AllPlanets\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start2=Enabled\/SPACE\/Spacecraft\/SPACE\/AllPlanets_SRP\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start3=Enabled\/SPACE\/Spacecraft\/SPACE\/ESM_JGM\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start4=Enabled\/SPACE\/Spacecraft\/SPACE\/ESM\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start5=Enabled\/SPACE\/CelestialObject\/SPACE\/Jupiter1\/SPACE\/\/SPACE\/
Start6=Enabled\/SPACE\/CelestialObject\/SPACE\/Mercury1\/SPACE\/\/SPACE\/
Start7=Enabled\/SPACE\/CelestialObject\/SPACE\/Venus1\/SPACE\/\/SPACE\/
Start8=Enabled\/SPACE\/CelestialObject\/SPACE\/Neptune1\/SPACE\/\/SPACE\/
Start9=Enabled\/SPACE\/CelestialObject\/SPACE\/Pluto1\/SPACE\/\/SPACE\/
Start10=Enabled\/SPACE\/CelestialObject\/SPACE\/Saturn1\/SPACE\/\/SPACE\/
Start11=Enabled\/SPACE\/CelestialObject\/SPACE\/Uranus1\/SPACE\/\/SPACE\/
Start12=Enabled\/SPACE\/CelestialObject\/SPACE\/Mars1\/SPACE\/\/SPACE\/
Start13=Enabled\/SPACE\/CelestialObject\/SPACE\/Moon1\/SPACE\/\/SPACE\/
Start14=Enabled\/SPACE\/CelestialObject\/SPACE\/Sun1\/SPACE\/\/SPACE\/
Start15=Enabled\/SPACE\/CelestialObject\/SPACE\/Earth1\/SPACE\/\/SPACE\/
Start16=Enabled\/SPACE\/Variable\/SPACE\/I\/SPACE\/\/SPACE\/
[FreeformScript2]
FreeFormLine1=\/SPACE\/FF_SolarSystem.COUpdateInterval = 0;\/END\/
FreeFormLine2=\/SPACE\/FF_SolarSystem.NPUpdateInterval = 60;\/END\/
FreeFormLine3=\/SPACE\/FF_SolarSystem.ComputePolarMotion = 1;\/END\/
FreeFormLine4=\/SPACE\/\/END\/
FreeFormLine5=\/SPACE\/AllPlanets.X = 406326.22661300009;\/END\/
FreeFormLine6=\/SPACE\/AllPlanets.Y = 177458.38761599999;\/END\/
FreeFormLine7=\/SPACE\/AllPlanets.Z = 145838.58078999998;\/END\/
FreeFormLine8=\/SPACE\/AllPlanets.VX = -0.517274673822;\/END\/
FreeFormLine9=\/SPACE\/AllPlanets.VY = 0.774650366561;\/END\/
FreeFormLine10=\/SPACE\/AllPlanets.VZ = 0.331416602654;\/END\/
FreeFormLine11=\/SPACE\/\/END\/
FreeFormLine12=\/SPACE\/AllPlanets_SRP.X = 406326.22661300009;\/END\/
FreeFormLine13=\/SPACE\/AllPlanets_SRP.Y = 177458.38761599999;\/END\/
FreeFormLine14=\/SPACE\/AllPlanets_SRP.Z = 145838.58078999998;\/END\/
FreeFormLine15=\/SPACE\/AllPlanets_SRP.VX = -0.517274673822;\/END\/
FreeFormLine16=\/SPACE\/AllPlanets_SRP.VY = 0.774650366561;\/END\/
FreeFormLine17=\/SPACE\/AllPlanets_SRP.VZ = 0.331416602654;\/END\/
FreeFormLine18=\/SPACE\/\/END\/
FreeFormLine19=\/SPACE\/ESM.X = 406326.22661300009;\/END\/
FreeFormLine20=\/SPACE\/ESM.Y = 177458.38761599999;\/END\/
FreeFormLine21=\/SPACE\/ESM.Z = 145838.58078999998;\/END\/
FreeFormLine22=\/SPACE\/ESM.VX = -0.517274673822;\/END\/
FreeFormLine23=\/SPACE\/ESM.VY = 0.774650366561;\/END\/
FreeFormLine24=\/SPACE\/ESM.VZ = 0.331416602654;\/END\/
FreeFormLine25=\/SPACE\/\/END\/
FreeFormLine26=\/SPACE\/ESM_JGM.X = 406326.22661300009;\/END\/
FreeFormLine27=\/SPACE\/ESM_JGM.Y = 177458.38761599999;\/END\/
FreeFormLine28=\/SPACE\/ESM_JGM.Z = 145838.580789999980;\/END\/
FreeFormLine29=\/SPACE\/ESM_JGM.VX = -0.517274673822;\/END\/
FreeFormLine30=\/SPACE\/ESM_JGM.VY = 0.774650366561;\/END\/
FreeFormLine31=\/SPACE\/ESM_JGM.VZ = 0.331416602654;\/END\/
[COMMAND_SECTION]
Number_Commands=26
