# $Id: Makefile 9490 2011-06-14 16:28:40Z tdnguye2 $
# GMAT: General Mission Analysis Tool.
# 
#  Copyright (c) 2002-2011 United States Government as represented by the
#  Administrator of The National Aeronautics and Space Administration.
#  All Other Rights Reserved.
#
# src level makefile 
#
# This file calls make on the src subfolders.

all: 
	cd base; make all;
	
rebuild: 
	cd src; make clean; make all;
	
clean:
	cd base; make clean;
	
