
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;


% MUST test separately, run-time
%While Sat.CoordinateSystem <= 4.0
%EndWhile ;


%----------------------------------------------------------
%  Test for improper use of closing branch command statement
%----------------------------------------------------------
%********* PreInterpreter Exceptions ***********
%While Sat.X == Sat.VX;
%While Sat.X < 2.0
%End;
% OK
%While 3.0 > 4.0
%EndIf;
% OK
%While Sat.Z < 3
%EndFor;

% 
1.0 While 3.0 < 4.0
EndWhile ;
