
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile1 WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

%----------------------------------------
%---------- Solvers
%----------------------------------------
Create FminconOptimizer OPT;
GMAT OPT.ShowProgress = true;
GMAT OPT.ReportStyle = Normal;
GMAT OPT.OptimizerTextFile = targeter_DefaultOPT.data;
GMAT OPT.MaximumIterations = 25;
GMAT OPT.UseCentralDifferences = false;


%---------------------------------------
%  Test for use of nonexistent resources
%---------------------------------------
%  
Optimize DNE
EndOptimize;  % 1

Optimize OPT DNE1.Y DNE2.Y
EndOptimize;  % 2

Optimize Sat.X OPT DNE;
EndOptimize;  % 3
Optimize DNE Sat.X;
EndOptimize;  % 4

%---------------------------------------
%  Test for improper use of parameters
%---------------------------------------

%---- Non-existent parameters
Optimize Sat.DNE
EndOptimize;  % 4

%---- Improper use of allowed parameters

%---- Disallowed parameters
Optimize WrongArray(2,1);
EndOptimize;  % 6

%---- Disallowed use of numbers
Optimize 1.0;
EndOptimize;  % 7
Optimize 1.0 1.0;
EndOptimize;  % 8
% Here, it doesn't see the Optimize, so it thinks it has 
% an extra EndOptimize ... hm ... - this is the general bug about the
% line number being wrong
%1.0 Optimize Sat.X;
%EndOptimize;  % 9

%---------------------------------------
%  Test for improper use of resources
%---------------------------------------
Optimize WrongSat;
EndOptimize;  % 10
Optimize WrongProp Sat.X;
EndOptimize;  % 11

%---------------------------------------
%  Test for missing elements
%---------------------------------------
Optimize 
EndOptimize;  % 12
Optimize % also testing the inline commentary here
EndOptimize;

%-------------------------------------------------
%  Test for improper use of conditional operators
%-------------------------------------------------
Optimize OPT < 3;
EndOptimize;  % 13
Optimize OpenGL < 3;
EndOptimize;  % 13

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%---  Missing Parenthesis ----
%  not applicable

%---  Missing curly brackets
%  not applicable

%--- Mixed incorrect brackets
% (Same bug as above - related to general wrong-line-number bug)
%(Optimize) OpenGL
%EndOptimize;  % 14
Optimize OPT (Sat.X)
EndOptimize;  % 15
Optimize (OPT)
EndOptimize;  % 16

Optimize (OPT Sat.X)
EndOptimize;  % 17
Optimize {OPT}
EndOptimize;  % 18
Optimize OPT {Sat.X}
EndOptimize;  % 19
Optimize {OPT Sat.X}
EndOptimize;  % 20

%--------------------------------
%-------  Comma Errors    -------
%--------------------------------

%---  Missing commas
%  not applicable

%---  Improper use of commas
%  Are these not allowed?
Optimize , OPT
EndOptimize;  % 21
Optimize , OPT Sat.X Sat.Y
EndOptimize;  % 21
Optimize OPT Sat.X, Sat.Y
EndOptimize;  % 22


%----------------------------------------------------------
%  Test for improper use of closing branch command statement
%----------------------------------------------------------
%  NOTE - These must each be tested separately - all OK
%Optimize OPT
%End;
%Optimize OPT
%EndIf;
%Optimize OPT 
%EndWhile;
%Optimize OPT;

