% IN PROGRESS ************************************* %
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat Sat2;
GMAT Sat.StateType = Cartesian;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FineBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;
Create String WrongString;

Maneuver ImpBurn(Sat);  % should be OK
%---------------------------------------
%  Use of nonexistent resources
%---------------------------------------
Maneuver DNE(Sat2);
Maneuver Sat.DNE(Sat2);
Maneuver ImpBurn(DNE)

%---------------------------------------
%  Improper use of resources
%---------------------------------------
Maneuver FinBurn(Sat2);   % should be an ImpulsiveBurn
Maneuver ImpBurn(sat.CoordinateSystem);
Maneuver ImpBurn(WrongProp);
Maneuver ImpBurn(WrongXYPlot);
Maneuver ImpBurn(WrongTank);
Maneuver ImpBurn(WrongCoordSys);

%---------------------------------------
%  Improper use of parameters

%---- Improper use of allowed parameters
%---------------------------------------
Maneuver WrongProp(Sat);
Maneuver sat.X(Sat2);


%---- Disallowed parameters
Maneuver WrongString(Sat);


%---------------------------------------
%  Improper use of real numbers
%---------------------------------------
1.0 Maneuver ImpBurn(Sat);
Maneuver 1.0(Sat);
Maneuver ImpBurn(12.0);

%-------------------------------------------------
%  Improper use of conditional operators
%-------------------------------------------------
Maneuver ImpBurn(Sat < 3);
Maneuver ImpBurn(0 == Sat2)

%---------------------------------------------------
%  Improper use of brackets, braces and parentheses
%---------------------------------------------------

%---  Missing Parentheses ----
Maneuver ImpBurn Sat;
Maneuver ImpBurn Sat2;


%---  Missing curly brackets
% N/A

%--- Miscellaneous bracket and parentheses errors
Maneuver ImpBurn{Sat};
Maneuver ImpBurn[Sat];
Maneuver (ImpBurn) Sat;
Maneuver [ImpBurn] Sat;
Maneuver {ImpBurn} Sat;
Maneuver ImpBurn (Sat
Maneuver ImpBurn Sat);


%---------------------------------------
%  Missing command elements
%---------------------------------------
Maneuver ImpBurn;
Maneuver (Sat);
 
%----------------------------------------------------------
%  Improper use of closing branch command statement
%----------------------------------------------------------
% N/A


%---------------------------------------
%  Improper use of spaces
%---------------------------------------
Maneuver ImpBurn (Sat);  
Maneuver ImpBurn (Sat2);  
Maneuver ImpBurn {Sat};
Maneuver ImpBurn [Sat];

%--------------------------------
%  Comma errors    
%--------------------------------

%---  Missing commas
% N/A


%---  Improper use of commas
Maneuver ImpBurn,(Sat);
Maneuver ImpBurn(Sat),
Maneuver, ImpBurn(Sat)


%-------------------------------
%  Closing branch command error
%-------------------------------
% N/A
