
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

NoOp;


%---------------------------------------
%  Test for use of nonexistent resources
%---------------------------------------
%  The script line is not output for these errors - now it is
NoOp DNE
NoOp Sat.X DNE1.Y DNE2.Y
NoOp Sat.X DNE;
NoOp DNE Sat.X;

%---------------------------------------
%  Test for improper use of parameters
%---------------------------------------

%---- Non-existent parameters
NoOp Sat.DNE

%---- Improper use of allowed parameters

%---- Disallowed parameters
NoOp WrongArray(2,1);

%---- Disallowed use of numbers
NoOp 1.0;
1.0 NoOp;

%---------------------------------------
%  Test for improper use of resources
%---------------------------------------
NoOp WrongSat;
NoOp WrongProp Sat.X;

%---------------------------------------
%  Test for missing elements
%---------------------------------------
NoOp OpenGL Sat.X

%-------------------------------------------------
%  Test for improper use of conditional operators
%-------------------------------------------------
NoOp OpenGL < 3;

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%---  Missing Parenthesis ----
%  not applicable

%---  Missing curly brackets
%  not applicable

%--- Mixed incorrect brackets
(NoOp) OpenGL
NoOp OpenGL (Sat.X)
NoOp (OpenGL)
NoOp (OpenGL Sat.X)
NoOp {OpenGL}
NoOp OpenGL {Sat.X}
NoOp {OpenGL Sat.X}

%----------------------------------------------------------
%  Test for improper use of closing branch command statement
%----------------------------------------------------------
%  not applicable

%--------------------------------
%-------  Comma Errors    -------
%--------------------------------

%---  Missing commas
%  not applicable

%---  Improper use of commas
%  Are these not allowed?
NoOp , OpenGL Sat.X Sat.Y
NoOp OpenGL Sat.X, Sat.Y

