
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

%***************************************************************
%--------------------------------------------------------------
%-----------  Command Exceptions !!!
%--------------------------------------------------------------
%***************************************************************
While WrongArray < Sat.X
EndWhile ;
While Array == WrongArray
EndWhile ;
While Sat.X <= WrongArray & Sat.X == Sat.X;
EndWhile ;
While Sat.X <= 1.0 & WrongArray >= Sat.X;
EndWhile ;

While Prop == 4
EndWhile ;

%***************************************************************
%--------------------------------------------------------------
%-----------  Interpreter Exceptions !!!
%--------------------------------------------------------------
%***************************************************************

%%---------------------------------------
%%  Test for use of nonexistent resourses
%%---------------------------------------
% 
While DNE.X <= 1;
EndWhile ;
While Sat.X == DNE;
EndWhile ;
While Sat.X < 100000 | Sat.Y > DNE;
EndWhile ;
While Sat.X < 100000 & Sat.DNE > 2;
EndWhile ;
While DNE < 100000 & 3 > 2;
EndWhile ;
While 4000 < DNE | 3 > 2;
EndWhile ;

%%---------------------------------------
%%  Test for improper use of parameters
%%---------------------------------------
%
%%---- Improper use of allowed parameters
%
%
%%---- Disallowed parameters:  Arrays are not allowed 
%%                             in if statements.
%********* Command Exceptions ***********
%///  While WrongArray < Sat.X
%///  EndWhile ;
%///  While Array == WrongArray
%///  EndWhile ;
%///  While Sat.X <= WrongArray & Sat.X == Sat.X;
%///  EndWhile ;
%///  While Sat.X <= 1.0 & WrongArray >= Sat.X;
%///  EndWhile ;
%
%%---------------------------------------
%%  Test for improper use of resources
%%---------------------------------------
% CRASH - no longer crashes - MUST test separately, run-time
% see If2.script
%While Sat.CoordinateSystem <= 4.0
%EndWhile ;
%  MUST retest this one in run-time 
%While Prop == 4
%EndWhile ;

%%---------------------------------------
%%  Test for missing elements
%%---------------------------------------
% OK now
While <= 3.0
EndWhile 
While Sat.X <= 
EndWhile 
While Sat.X <= 3 | > Sat.Y
EndWhile 
While Sat.X <= 3 | 3.4 > 
EndWhile 
While Sat.X <=  | 3.4 > 5
EndWhile 
While Sat.X <= 3 | 3.4 > 
EndWhile 

%%-------------------------------------------------
%%  Test for improper use of conditional operators
%%-------------------------------------------------
%********* Command Exceptions ***********
%///  While 3 = 4
%///  EndWhile ;
%///  While 3 =< 4
%///  EndWhile 
%///  While 3 =~ 4
%///  EndWhile 
%///  While 3 => 4
%///  EndWhile 
%///  While 3 == 4 & 4 = 4
%///  EndWhile ;
%///  While 3 =< 4 | 4 <= 5
%///  EndWhile 
%///  While 3 =~ 4 & 5 ~= 7
%///  EndWhile 
%///  While 5 <= 9 | 3 => 4
%///  EndWhile 
While 3 = 4
EndWhile ;
While 3 =< 4
EndWhile 
While 3 =~ 4
EndWhile 
While 3 => 4
EndWhile 
While 3 == 4 & 4 = 4
EndWhile ;
While 3 =< 4 | 4 <= 5
EndWhile 
While 3 =~ 4 & 5 ~= 7
EndWhile 
While 5 <= 9 | 3 => 4
EndWhile 

While 3 < = 4;
EndWhile ;
While 3 = = 4;
EndWhile ;
While 5 > = 2;
EndWhile 
While 3 <= 4 AND 4 >= 6
EndWhile 
While 3 == 4 OR 4 == 6
EndWhile 

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%  Check parenthesis
% CRASH: On build and run.  Have to have this in a script by itself!! - OK now, does not crash
While ( Sat.X == Sat.X );
EndWhile 
While  Sat.X == Sat.X );
EndWhile 
% CRASH - no longer crashes
While  (Sat.X == Sat.X ;
EndWhile 
While Sat.X == Sat.Y & ( Sat.VX == Sat.VY
EndWhile 
While (Sat.X == Sat.Y | Sat.VY == Sat.VZ)
EndWhile ;

While (Sat.X == Sat.Y) & (Sat.VX >= 3)
EndWhile ;

%  Check curly bracktets
While { Sat.X == Sat.X };
EndWhile 
While  Sat.X == Sat.X };
EndWhile 
While  {Sat.X == Sat.X ;
EndWhile 
While Sat.X == Sat.Y & { Sat.VX == Sat.VY
EndWhile 
While {Sat.X == Sat.Y | Sat.VY == Sat.VZ}
EndWhile ;
While {Sat.X == Sat.Y} & {Sat.VX >= 3}
EndWhile ;


%----------------------------------------------------------
%  Test for erroneous text after the Else statement
%----------------------------------------------------------
While 3 < 4
Else other-stuff-that-should-not-be-here
EndWhile ;
While 3 < 4
Else % but inline comments should be OK
EndWhile ;

