
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

%---------------------------------------
%  Test for use of nonexistent resources
%---------------------------------------
%  Errors on these two lines are caught in the final pass
Report ReportFile DNE.X 
Report ReportFile Sat.X DNE1.Y DNE2.Y
Report ReportFile Sat.X DNE;
Report DNE Sat.X;

%---------------------------------------
%  Test for improper use of parameters
%---------------------------------------

%---- Non-existent parameters
Report ReportFile Sat.DNE

%---- Improper use of allowed parameters

%---- Disallowed parameters
%  
Report ReportFile WrongArray(2,1);  % this is OK
Report ReportFile WrongProp;  % this should not be OK

%---- Disallowed use of numbers
Report ReportFile 1.0;
Report 1.0 1.0;
1.0 ReportFile Sat.X;

%---------------------------------------
%  Test for improper use of resources
%---------------------------------------
Report ReportFile WrongSat;
Report WrongProp Sat.X;

%---------------------------------------
%  Test for missing elements
%---------------------------------------
ReportFile Sat.X
Report Sat.X
Report ReportFile

%-------------------------------------------------
%  Test for improper use of conditional operators
%-------------------------------------------------
Report ReportFile Sat.X < 3;

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%---  Missing Parenthesis ----
%  not applicable

%---  Missing curly brackets
%  not applicable

%--- Mixed incorrect brackets
Report (ReportFile) Sat.X
Report ReportFile (Sat.X)
Report (ReportFile) Sat.X
Report (ReportFile Sat.X)
Report {ReportFile} Sat.X
Report ReportFile {Sat.X}
Report {ReportFile} Sat.X
Report {ReportFile Sat.X}

%----------------------------------------------------------
%  Test for improper use of closing branch command statement
%----------------------------------------------------------
%  not applicable

%--------------------------------
%-------  Comma Errors    -------
%--------------------------------

%---  Missing commas
%  not applicable

%---  Improper use of commas
%  Are these not allowed?
Report , ReportFile Sat.X Sat.Y
Report ,ReportFile Sat.X Sat.Y
Report ReportFile, Sat.X Sat.Y
Report ReportFile Sat.X, Sat.Y
Report ReportFile Sat.X Sat.Y ,
