% IN PROGRESS ************************************* %
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat;
GMAT Sat.StateType = Cartesian;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;
Create FminconOptimizer SQPfmincon;
Create String WrongString;
GMAT SQPfmincon.DiffMaxChange = 0.01;      % Real number
GMAT SQPfmincon.DiffMinChange = 0.000001;  % Real number
GMAT SQPfmincon.MaxFunEvals   = 1000;    % Real number
GMAT SQPfmincon.MaxIter       = 250;     % Real number
GMAT SQPfmincon.TolX          = 0.01;    % Real number
GMAT SQPfmincon.TolFun        = 0.0001;  % Real number
GMAT SQPfmincon.TolCon        = 0.0001;  % Real number
GMAT SQPfmincon.DerivativeCheck = Off;   % {On, Off}
GMAT SQPfmincon.Diagnostics     = On;    % {On, Off}
GMAT SQPfmincon.Display         = Iter   % {Iter, Off, Notify, Final}
GMAT SQPfmincon.GradObj         = Off;   % {On, Off}
GMAT SQPfmincon.GradConstr      = Off;   % {On, Off}

Optimize SQPfmincon; % test inside an Optimize loop

NonlinearConstraint SQPfmincon (Sat.SMA = 7000);  % should be OK
NonlinearConstraint SQPfmincon (Array(1,1) >= 0);   % should be OK
%---------------------------------------
%  Use of nonexistent resources
%---------------------------------------
NonlinearConstraint DNE (Sat.SMA = 6877);
NonlinearConstraint DNE (WrongArray);
NonlinearConstraint Sat.DNE (Var = 0);

%---------------------------------------
%  Improper use of resources
%---------------------------------------
NonlinearConstraint SQPfmincon(sat.CoordinateSystem = 1.0);
NonlinearConstraint SQPfmincon(WrongProp = Prop);

%---------------------------------------
%  Improper use of parameters

%---- Improper use of allowed parameters
%---------------------------------------
NonlinearConstraint WrongProp(Var = 0);
NonlinearConstraint sat.X(Var = 0);


%---- Disallowed parameters
NonlinearConstraint WrongString(Var = 0);


%---------------------------------------
%  Improper use of real numbers
%---------------------------------------
1.0 NonlinearConstraint SQPfmincon (Var = 0);
NonlinearConstraint 1.0(Var= 0);
NonlinearConstraint SQPfmincon(12.0 >= Var);

%-------------------------------------------------
%  Improper use of conditional operators
%-------------------------------------------------
NonlinearConstraint SQPfmincon(Var < 3);
NonlinearConstraint SQPfmincon(Array(1,1) == 0)
NonlinearConstraint SQPfmincon(Array(1,1) =< 0)
NonlinearConstraint SQPfmincon(Array(1,1) => 0)
NonlinearConstraint SQPfmincon(Var => Array(1.1))

%---------------------------------------------------
%  Improper use of brackets, braces and parentheses
%---------------------------------------------------

%---  Missing Parentheses ----
NonlinearConstraint SQPfmincon Var = 0;
NonlinearConstraint SQPfmincon 1.0 >= Array(1,1);


%---  Missing curly brackets
% N/A

%--- Miscellaneous bracket and parentheses errors
NonlinearConstraint SQPfmincon{Var = 0};
NonlinearConstraint SQPfmincon[0 <= Var];
NonlinearConstraint (SQPfmincon) Var >= 1;
NonlinearConstraint [SQPfmincon] Var = 0;
NonlinearConstraint {SQPfmincon} Var = 0;
NonlinearConstraint SQPfmincon (Var = 0
NonlinearConstraint SQPfmincon Var = 0);


%---------------------------------------
%  Missing command elements
%---------------------------------------
NonlinearConstraint SQPfmincon;
NonlinearConstraint (Var = 0);
 
%----------------------------------------------------------
%  Improper use of closing branch command statement
%----------------------------------------------------------
% N/A

%--------------------------------
%  Comma errors    
%--------------------------------

%---  Missing commas
% N/A


%---  Improper use of commas
NonlinearConstraint SQPfmincon, (Var = 0);
NonlinearConstraint SQPfmincon (0=Var),
NonlinearConstraint, SQPfmincon (Var >= 0)


%-------------------------------
%  Closing branch command error
%-------------------------------
% N/A
EndOptimize;