
%---------------------------------------------------------------
%  These objects are for use in commands. They are necessary 
%  to test when resources are not used correctly in commands.
%---------------------------------------------------------------
Create Spacecraft Sat WrongSat;
Create Thruster Thruster WrongThruster;
Create FuelTank WrongTank;
Create Formation Formation WrongFormation
Create ImpulsiveBurn ImpBurn WrongImpBurn
Create FiniteBurn FiniteBurn WrongFiniteBurn
Create Propagator Prop WrongProp
Create OpenGLPlot OpenGL WrongOpenGL
%Create XYPlot XYPlot WrongXYPlot
Create XYPlot XYPlot1 WrongXYPlot
XYPlot1.IndVar = Sat.X;
WrongXYPlot.IndVar = WrongSat.X;
Create ReportFile ReportFile WrongReportFile
Create Variable Var WrongVar
Create Array Array[3,3] WrongArray[3,3]
Create CoordinateSystem CoordSys WrongCoordSys;

%***************************************************************
%--------------------------------------------------------------
%-----------  Command Exceptions !!!
%--------------------------------------------------------------
%***************************************************************
If WrongArray < Sat.X
EndIf;
If Array == WrongArray
EndIf;
If Sat.X <= WrongArray & Sat.X == Sat.X;
EndIf;
If Sat.X <= 1.0 & WrongArray >= Sat.X;
EndIf;

If Prop == 4
EndIf;

%***************************************************************
%--------------------------------------------------------------
%-----------  Interpreter Exceptions !!!
%--------------------------------------------------------------
%***************************************************************

%%---------------------------------------
%%  Test for use of nonexistent resourses
%%---------------------------------------
% 
If DNE.X <= 1;
EndIf;
If Sat.X == DNE;
EndIf;
If Sat.X < 100000 | Sat.Y > DNE;
EndIf;
If Sat.X < 100000 & Sat.DNE > 2;
EndIf;
If DNE < 100000 & 3 > 2;
EndIf;
If 4000 < DNE | 3 > 2;
EndIf;

%%---------------------------------------
%%  Test for improper use of parameters
%%---------------------------------------
%
%%---- Improper use of allowed parameters
%
%
%%---- Disallowed parameters:  Arrays are not allowed 
%%                             in if statements.
%********* Command Exceptions ***********
%///  If WrongArray < Sat.X
%///  EndIf;
%///  If Array == WrongArray
%///  EndIf;
%///  If Sat.X <= WrongArray & Sat.X == Sat.X;
%///  EndIf;
%///  If Sat.X <= 1.0 & WrongArray >= Sat.X;
%///  EndIf;
%
%%---------------------------------------
%%  Test for improper use of resources
%%---------------------------------------
% CRASH - no longer crashes - MUST test separately, run-time
% see If2.script
%If Sat.CoordinateSystem <= 4.0
%EndIf;
%  MUST retest this one in run-time 
%If Prop == 4
%EndIf;

%%---------------------------------------
%%  Test for missing elements
%%---------------------------------------
% OK now
If <= 3.0
EndIf
If Sat.X <= 
EndIf
If Sat.X <= 3 | > Sat.Y
EndIf
If Sat.X <= 3 | 3.4 > 
EndIf
If Sat.X <=  | 3.4 > 5
EndIf
If Sat.X <= 3 | 3.4 > 
EndIf

%%-------------------------------------------------
%%  Test for improper use of conditional operators
%%-------------------------------------------------
%********* Command Exceptions ***********
%///  If 3 = 4
%///  EndIf;
%///  If 3 =< 4
%///  EndIf
%///  If 3 =~ 4
%///  EndIf
%///  If 3 => 4
%///  EndIf
%///  If 3 == 4 & 4 = 4
%///  EndIf;
%///  If 3 =< 4 | 4 <= 5
%///  EndIf
%///  If 3 =~ 4 & 5 ~= 7
%///  EndIf
%///  If 5 <= 9 | 3 => 4
%///  EndIf
If 3 = 4
EndIf;
If 3 =< 4
EndIf
If 3 =~ 4
EndIf
If 3 => 4
EndIf
If 3 == 4 & 4 = 4
EndIf;
If 3 =< 4 | 4 <= 5
EndIf
If 3 =~ 4 & 5 ~= 7
EndIf
If 5 <= 9 | 3 => 4
EndIf

If 3 < = 4;
EndIf;
If 3 = = 4;
EndIf;
If 5 > = 2;
EndIf
If 3 <= 4 AND 4 >= 6
EndIf
If 3 == 4 OR 4 == 6
EndIf

%---------------------------------------------------
%  Test for improper use of brackets and parenthesis
%---------------------------------------------------

%  Check parenthesis
% CRASH: On build and run.  Have to have this in a script by itself!! - OK now, does not crash
If ( Sat.X == Sat.X );
EndIf
If  Sat.X == Sat.X );
EndIf
% CRASH - no longer crashes
If  (Sat.X == Sat.X ;
EndIf
If Sat.X == Sat.Y & ( Sat.VX == Sat.VY
EndIf
If (Sat.X == Sat.Y | Sat.VY == Sat.VZ)
EndIf;

If (Sat.X == Sat.Y) & (Sat.VX >= 3)
EndIf;

%  Check curly bracktets
If { Sat.X == Sat.X };
EndIf
If  Sat.X == Sat.X };
EndIf
If  {Sat.X == Sat.X ;
EndIf
If Sat.X == Sat.Y & { Sat.VX == Sat.VY
EndIf
If {Sat.X == Sat.Y | Sat.VY == Sat.VZ}
EndIf;
If {Sat.X == Sat.Y} & {Sat.VX >= 3}
EndIf;


%----------------------------------------------------------
%  Test for erroneous text after the Else statement
%----------------------------------------------------------
If 3 < 4
Else other-stuff-that-should-not-be-here
EndIf;
If 3 < 4
Else % but inline comments should be OK
EndIf;

