function CellOut = FFPreamble(outputfile);
CellOut = {'Define Procedure FF_Match_GMAT_Report(Spacecraft SC, ReportInterface File);';
'Variable i;';
'Variable ColumnWidth = 30;';
'StringArray ScState[8];';
'String space = ''                                                         '';';
'String tmpString;';
' ';
' ';
' ';
'ScState[0] = SC.Epoch.Format(''%16.16f'');';
'ScState[1] = SC.X.Format(''%16.16f'');';
'ScState[2] = SC.Y.Format(''%16.16f'');';
'ScState[3] = SC.Z.Format(''%16.16f'');';
'ScState[4] = SC.VX.Format(''%16.16f'');';
'ScState[5] = SC.VY.Format(''%16.16f'');';
'ScState[6] = SC.VZ.Format(''%16.16f'');';
'ScState[7] = SC.MassTotal.Format(''%16.16f'');';
' ';
'For i = 0 to ScState.Dimension - 1 step 1;';
'tmpString = ScState[i];';
'ScState[i] = StringConcat(SubString(ScState[i],0,18),SubString(space,0,ColumnWidth - 18));';
'End;';
' ';
'Report StringConcat(ScState[0],ScState[1],ScState[2],ScState[3],ScState[4],ScState[5],ScState[6],ScState[7])';
'		to File without headers without pad;';
' ';
'EndProcedure;';
' ';
'StringArray splitted[20];';
'FF_Preferences.MissionPlanFilename.Split(''.'',splitted);';
'Report splitted[0];';
' ';
'ReportInterface FF_GMAT_Report;'
['FF_GMAT_Report.Filename = ''',outputfile,''';'];
'FF_GMAT_Report.Append = 0;';
' ';
'Create ForceModel fm;';
'fm.Sun 	 = 0;';
'fm.Mercury = 0;';
'fm.Venus = 0;';
'fm.Earth = 1;';
'fm.Moon  = 0;';
'fm.Mars  = 0;';
'fm.Jupiter = 0;';
'fm.Saturn = 0;';
'fm.Uranus = 0;';
'fm.Neptune= 0;';
'fm.Pluto = 0;';
' ';
'fm.Drag  = 0;';
'fm.SRP   = 0;';
'fm.Lift  = 0;';
' ';
'fm.PlanetFieldType[2] = 0; //Earth is index 2, Mars 3, Venus 1 , bla bla bla';
' ';
'Create RK89 prop(fm);';
'prop.FixedStep = 1;';
'prop.StepSize  = 60;';
'prop.Tolerance = 1e-12;';
' '};
end

