[COMMAND1]
Command1=Enabled\/SPACE\/FreeForm\/SPACE\/Freeform Script\/SPACE\/FreeformScript2\/SPACE\/\/SPACE\/
[COMMAND2]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/ISS.ElapsedDays <= 1\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND3]
Command1=Enabled\/SPACE\/Report\/SPACE\/ISS.ElapsedMinutes<15,9>, ISS.X<15,9>, ISS.Y<15,9>, ISS.Z<15,9>, ISS.VX<15,9>, ISS.VY<15,9>, ISS.VZ<15,9>\/Delimit\/ISS.ElapsedMinutes<15,9>\/Delimit\/ISS.X<15,9>\/Delimit\/ISS.Y<15,9>\/Delimit\/ISS.Z<15,9>\/Delimit\/ISS.VX<15,9>\/Delimit\/ISS.VY<15,9>\/Delimit\/ISS.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND4]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 12 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[FORMAT_SECTION]
Position=103
ProjectDir=C:\GMAT_CVSdocs\RefSoftFiles\FreeFlyerData\AllPlanetsPM\
ProjectType=1
NumLines=45
0CWObjectList0=225
0CWObjectListLast0=199
0CWObjectList1=225
0CWObjectListLast1=199
0CWObjectList2=-1
0CWObjectListLast2=-1
0CWObjectList3=391
0CWObjectListLast3=460
1CWObjectList0=225
1CWObjectListLast0=199
1CWObjectList1=225
1CWObjectListLast1=199
1CWObjectList2=-1
1CWObjectListLast2=-1
1CWObjectList3=391
1CWObjectListLast3=460
2CWObjectList0=228
2CWObjectListLast0=199
2CWObjectList1=228
2CWObjectListLast1=199
2CWObjectList2=-1
2CWObjectListLast2=-1
2CWObjectList3=402
2CWObjectListLast3=460
3CWObjectList0=231
3CWObjectListLast0=201
3CWObjectList1=-1
3CWObjectListLast1=-1
3CWObjectList2=154
3CWObjectListLast2=134
3CWObjectList3=459
3CWObjectListLast3=509
4CWObjectList0=83
4CWObjectListLast0=72
4CWObjectList1=222
4CWObjectListLast1=193
4CWObjectList2=333
4CWObjectListLast2=289
4CWObjectList3=205
4CWObjectListLast3=289
CWMDS0=69
CWMDSLast0=61
CWMDS1=335
CWMDSLast1=295
CWMDS2=335
CWMDSLast2=312
CWMDS3=60
CWMDSLast3=148
ActivePage=1
MDSRecord=1
[COMMAND5]
Command1=Enabled\/SPACE\/Step\/SPACE\/ISS\/SPACE\/\/SPACE\/
[COMMAND6]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND7]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND8]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/GEO.ElapsedDays <= 7\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND9]
Command1=Enabled\/SPACE\/Report\/SPACE\/GEO.ElapsedMinutes<15,9>, GEO.X<15,9>, GEO.Y<15,9>, GEO.Z<15,9>, GEO.VX<15,9>, GEO.VY<15,9>, GEO.VZ<15,9>\/Delimit\/GEO.ElapsedMinutes<15,9>\/Delimit\/GEO.X<15,9>\/Delimit\/GEO.Y<15,9>\/Delimit\/GEO.Z<15,9>\/Delimit\/GEO.VX<15,9>\/Delimit\/GEO.VY<15,9>\/Delimit\/GEO.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_GEO_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND10]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 10 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND11]
Command1=Enabled\/SPACE\/Step\/SPACE\/GEO\/SPACE\/\/SPACE\/
[COMMAND12]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND13]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND14]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/GPS.ElapsedDays <= 2\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND15]
Command1=Enabled\/SPACE\/Report\/SPACE\/GPS.ElapsedMinutes<15,9>, GPS.X<15,9>, GPS.Y<15,9>, GPS.Z<15,9>, GPS.VX<15,9>, GPS.VY<15,9>, GPS.VZ<15,9>\/Delimit\/GPS.ElapsedMinutes<15,9>\/Delimit\/GPS.X<15,9>\/Delimit\/GPS.Y<15,9>\/Delimit\/GPS.Z<15,9>\/Delimit\/GPS.VX<15,9>\/Delimit\/GPS.VY<15,9>\/Delimit\/GPS.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_GPS_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND16]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 2 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND17]
Command1=Enabled\/SPACE\/Step\/SPACE\/GPS\/SPACE\/\/SPACE\/
[COMMAND18]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND19]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND20]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/SunSync.ElapsedDays <= 1\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND21]
Command1=Enabled\/SPACE\/Report\/SPACE\/SunSync.ElapsedDays<15,9>, SunSync.X<15,9>, SunSync.Y<15,9>, SunSync.Z<15,9>, SunSync.VX<15,9>, SunSync.VY<15,9>, SunSync.VZ<15,9>\/Delimit\/SunSync.ElapsedDays<15,9>\/Delimit\/SunSync.X<15,9>\/Delimit\/SunSync.Y<15,9>\/Delimit\/SunSync.Z<15,9>\/Delimit\/SunSync.VX<15,9>\/Delimit\/SunSync.VY<15,9>\/Delimit\/SunSync.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_SunSync_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND22]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 12 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND23]
Command1=Enabled\/SPACE\/Step\/SPACE\/SunSync\/SPACE\/\/SPACE\/
[COMMAND24]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND25]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND26]
Command1=Enabled\/SPACE\/While\/SPACE\/Expanded\/SPACE\/Molniya.ElapsedDays <= 3\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[CopyOfISS]
EphemFileType=Unknown
UseEphem=0
[COMMAND27]
Command1=Enabled\/SPACE\/Report\/SPACE\/Molniya.ElapsedMinutes<15,9>, Molniya.X<15,9>, Molniya.Y<15,9>, Molniya.Z<15,9>, Molniya.VX<15,9>, Molniya.VY<15,9>, Molniya.VZ<15,9>\/Delimit\/Molniya.ElapsedMinutes<15,9>\/Delimit\/Molniya.X<15,9>\/Delimit\/Molniya.Y<15,9>\/Delimit\/Molniya.Z<15,9>\/Delimit\/Molniya.VX<15,9>\/Delimit\/Molniya.VY<15,9>\/Delimit\/Molniya.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_Molniya_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND28]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 60 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND29]
Command1=Enabled\/SPACE\/Step\/SPACE\/Molniya\/SPACE\/\/SPACE\/
[COMMAND30]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND31]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND32]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 366 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND33]
Command1=Enabled\/SPACE\/FreeForm\/SPACE\/Freeform Script\/SPACE\/FreeformScript3\/SPACE\/\/SPACE\/
[COMMAND34]
Command1=Enabled\/SPACE\/Report\/SPACE\/DeepSpace.EpochUTC<15,9>, DeepSpace.X<15,9>, DeepSpace.Y<15,9>, DeepSpace.Z<15,9>, DeepSpace.VX<15,9>, DeepSpace.VY<15,9>, DeepSpace.VZ<15,9>\/Delimit\/DeepSpace.EpochUTC<15,9>\/Delimit\/DeepSpace.X<15,9>\/Delimit\/DeepSpace.Y<15,9>\/Delimit\/DeepSpace.Z<15,9>\/Delimit\/DeepSpace.VX<15,9>\/Delimit\/DeepSpace.VY<15,9>\/Delimit\/DeepSpace.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_DeepSpaceEEq_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND35]
Command1=Enabled\/SPACE\/Step\/SPACE\/DeepSpace to (DeepSpace.ElapsedDaysFromEpoch(OldEpoch) = 1)\/SPACE\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND36]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND37]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND38]
Command1=Enabled\/SPACE\/For\/SPACE\/Expanded\/SPACE\/I = 1 to 366 step 1\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND39]
Command1=Enabled\/SPACE\/FreeForm\/SPACE\/Freeform Script\/SPACE\/FreeformScript3\/SPACE\/\/SPACE\/
[COMMAND40]
Command1=Enabled\/SPACE\/Report\/SPACE\/DeepSpace.EpochUTC<15,9>, DeepSpace.X<15,9>, DeepSpace.Y<15,9>, DeepSpace.Z<15,9>, DeepSpace.VX<15,9>, DeepSpace.VY<15,9>, DeepSpace.VZ<15,9>\/Delimit\/DeepSpace.EpochUTC<15,9>\/Delimit\/DeepSpace.X<15,9>\/Delimit\/DeepSpace.Y<15,9>\/Delimit\/DeepSpace.Z<15,9>\/Delimit\/DeepSpace.VX<15,9>\/Delimit\/DeepSpace.VY<15,9>\/Delimit\/DeepSpace.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_DeepSpaceEEq_AllPlanets_0_0_0.report\/SPACE\/\/SPACE\/
[COMMAND41]
Command1=Enabled\/SPACE\/Step\/SPACE\/DeepSpace to (DeepSpace.ElapsedDaysFromEpoch(OldEpoch) = 1)\/SPACE\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND42]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND43]
Command1=Enabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND44]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/ReportTime = ( CountTime * SS )\/Delimit\/Variable\/Operator\/Variable\/Operator\/Variable\/SPACE\/\/SPACE\/
[COMMAND45]
Command1=Disabled\/SPACE\/If\/SPACE\/Expanded\/SPACE\/ReportTime = 600\/Delimit\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND46]
Command1=Disabled\/SPACE\/Report\/SPACE\/ISS.ElapsedDays<15,9>, ISS.X<15,9>, ISS.Y<15,9>, ISS.Z<15,9>, ISS.VX<15,9>, ISS.VY<15,9>, ISS.VZ<15,9>, CountTime<15,9>, ISS.ElapsedSeconds<15,9>\/Delimit\/ISS.ElapsedDays<15,9>\/Delimit\/ISS.X<15,9>\/Delimit\/ISS.Y<15,9>\/Delimit\/ISS.Z<15,9>\/Delimit\/ISS.VX<15,9>\/Delimit\/ISS.VY<15,9>\/Delimit\/ISS.VZ<15,9>\/Delimit\/CountTime<15,9>\/Delimit\/ISS.ElapsedSeconds<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0.Report\/SPACE\/\/SPACE\/
[COMMAND47]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/CountTime = ( 0 )\/Delimit\/Variable\/Operator\/Number\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND48]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND49]
Command1=Disabled\/SPACE\/Assignment\/SPACE\/CountTime = ( CountTime + 1 )\/Delimit\/Variable\/Operator\/Variable\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND50]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[COMMAND51]
Command1=Disabled\/SPACE\/While\/SPACE\/Collapsed\/SPACE\/CopyOfISS.ElapsedDays < 1\/Delimit\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND52]
Command1=Disabled\/SPACE\/View\/SPACE\/CopyOfISS\/SPACE\/\/SPACE\/
[COMMAND53]
Command1=Disabled\/SPACE\/Report\/SPACE\/CopyOfISS.ElapsedMinutes<15,9>, CopyOfISS.X<15,9>, CopyOfISS.Y<15,9>, CopyOfISS.Z<15,9>, CopyOfISS.VX<15,9>, CopyOfISS.VY<15,9>, CopyOfISS.VZ<15,9>\/Delimit\/CopyOfISS.ElapsedMinutes<15,9>\/Delimit\/CopyOfISS.X<15,9>\/Delimit\/CopyOfISS.Y<15,9>\/Delimit\/CopyOfISS.Z<15,9>\/Delimit\/CopyOfISS.VX<15,9>\/Delimit\/CopyOfISS.VY<15,9>\/Delimit\/CopyOfISS.VZ<15,9>\/Delimit\/Report Headers\/Delimit\/Include Headers\/SPACE\/FF_ISS_Earth_0_0_0_check.Report\/SPACE\/\/SPACE\/
[COMMAND54]
Command1=Disabled\/SPACE\/Step\/SPACE\/CopyOfISS to (CopyOfISS.ElapsedMinutes < 10)\/SPACE\/Object Parameter\/Operator\/Number\/SPACE\/\/SPACE\/
[COMMAND55]
Command1=Disabled\/SPACE\/End\/SPACE\/\/SPACE\/
[ISS]
EphemFileType=Unknown
UseEphem=0
[GEO]
EphemFileType=Unknown
UseEphem=0
[GPS]
EphemFileType=Unknown
UseEphem=0
[SunSync]
EphemFileType=Unknown
UseEphem=0
[Molniya]
EphemFileType=Unknown
UseEphem=0
[DeepSpace]
EphemFileType=Unknown
UseEphem=0
[START_SECTION]
Start1=Enabled\/SPACE\/Spacecraft\/SPACE\/ISS\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start2=Enabled\/SPACE\/Spacecraft\/SPACE\/GEO\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start3=Enabled\/SPACE\/Spacecraft\/SPACE\/GPS\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start4=Enabled\/SPACE\/Spacecraft\/SPACE\/SunSync\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start5=Enabled\/SPACE\/Spacecraft\/SPACE\/Molniya\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start6=Enabled\/SPACE\/Spacecraft\/SPACE\/DeepSpace\/SPACE\/\/SPACE\/0\/SPACE\/0\/SPACE\/0\/SPACE\/\/SPACE\/Unknown\/SPACE\/
Start7=Enabled\/SPACE\/Variable\/SPACE\/I\/SPACE\/\/SPACE\/
Start8=Enabled\/SPACE\/Variable\/SPACE\/OldEpoch\/SPACE\/\/SPACE\/
[FreeformScript2]
FreeFormLine1=\/SPACE\/FF_SolarSystem.COUpdateInterval = 0;\/END\/
FreeFormLine2=\/SPACE\/FF_SolarSystem.NPUpdateInterval = 60;\/END\/
FreeFormLine3=\/SPACE\/FF_SolarSystem.ComputePolarMotion = 1;\/END\/
[FreeformScript3]
FreeFormLine1=\/SPACE\/OldEpoch = DeepSpace.Epoch;\/END\/
[COMMAND_SECTION]
Number_Commands=36
